### ISSUE TITLE
differentiate mindailyrate for currencies

### ISSUE THREAD

**Issue by aribo** [Mikadily/poloniexlendingbot#101]
Possible to create different mindailyrate for different currencies?

**Comment by rnevet** [comment]
In the configuration file:

#custom config per coin, useful when closing positions etc.
#syntax: ["COIN:mindailyrate:maxactiveamount",...]
#if maxactive amount is 0 - stop lending this coin. in the future you'll be able to limit amount to be lent.
#coinconfig = ["BTC:0.18:1","CLAM:0.6:1"]
