### ISSUE TITLE
Error canceling loan order

### ISSUE THREAD

**Issue by xR2** [Mikadily/poloniexlendingbot#106]
I've just restarted the bot, with new API (deleted the old) and keep getting this error.
Isn't the bot been recognized by poloniex ?

> Obtaining settings from config file.
> Welcome to Poloniex Lending Bot
> Started WebServer, lendingbot status available at http://127.0.0.1:8000/lendingbot.html
> 2016-09-07 16:48:50
> Traceback (most recent call last):
>   File "C:\poloniexlendingbot-master\lendingbot.py", line 458, in <module>
>     cancelAndLoanAll()
>   File "C:\poloniexlendingbot-master\lendingbot.py", line 286, in cancelAndLoanAll
>     msg = bot.cancelLoanOffer(cur,offer['id'])
>   File "C:\poloniexlendingbot-master\poloniex.py", line 157, in cancelLoanOffer
>     return self.api_query('cancelLoanOffer',{"currency":currency,"orderNumber":orderNumber})
>   File "C:\poloniexlendingbot-master\poloniex.py", line 68, in api_query
>     jsonRet = _read_response(ret)
>   File "C:\poloniexlendingbot-master\poloniex.py", line 38, in _read_response
>     raise PoloniexApiError(data['error'])
> PoloniexApiError: Error canceling loan order, or you are not the person who placed it.

**Comment by Evanito** [comment]
Likely solved by #107
