### ISSUE TITLE
ERROR: 'provided'

### ISSUE THREAD

**Issue by WesleyThurner** [Mikadily/poloniexlendingbot#11]
The bot was working fine for me, but I just started reciveing the following error during updates:
<date> <time> ERROR: 'provided'

I did a fresh install of Ubuntu 14.04 and still had the same issue.  Did the API get updated? or could it be an update within Ubuntu?

Also, is there any more info I can provide?

RESOLVED: I tracked it down to issues with my API keys.  I believe there is security mechanisms in place with the APIs that detect changes in IPs, etc.  I got a new key for each system and it works fine.

**Comment by WesleyThurner** [comment]
I got it running again on another fresh install without internet connectivity and no updates.  I believe an update in the Ubuntu repository breaks something.

**Comment by Mikadily** [comment]
That's an interesting find. Thanks.

**Comment by WesleyThurner** [comment]
Glad it was useful,  The confusing part was the error response.  I could not tell if the response was truncated.  If possible, it would be nice to see more of the error from poloniex.
