### ISSUE TITLE
Viewing http://127.0.0.1:8000/lendingbot.html on amazon ec2

### ISSUE THREAD

**Issue by burtnderson** [Mikadily/poloniexlendingbot#110]
Does anyone know how to view this from either inside an amazon ec2 instance or from my browser? I can see it while running locally, but now I'm running the bot from a vps and can't connect. Thanks.

**Comment by rnevet** [comment]
2 options:
1. If you already have a webserver on the ec2 instance, copy the www folder into an accessible area of your webserver. Set the json output folder to match.
2. You'll need to set the Host in code from 127.0.0.1 to your server IP.
