### ISSUE TITLE
Max to lent

### ISSUE THREAD

**Issue by prfiredragon** [Mikadily/poloniexlendingbot#116]
I made the feature, to choose the amount or percent you want to lent. I am testing it before make the pull request. but it includes the changes on the https://github.com/Mikadily/poloniexlendingbot/pull/112

in the config is like that
```
#Max amount to lent. if set to 0 or commented the bot will check for maxpercenttolent.
#maxtolent = 0

#Max percent to lent. if set to 0 or commented the bot will lent the 100%.
#maxpercenttolent = 0

#syntax: ["COIN:mindailyrate:maxactiveamount:maxtolent:maxpercenttolent",...]
#if maxactive amount is 0 - stop lending this coin. in the future you'll be able to limit amount to be lent.
#if maxtolent is 0 - check for maxpercenttolent.
#if maxpercenttolent is 0 - 100% is going to be lent.
#coinconfig = ["BTC:0.18:1:0:0","CLAM:0.6:1:0:0"]
```

```
parser.add_argument("-maxlent", "--maxtolent", help="Max amount to lent. if set to 0 the bot will check for maxpercenttolent.")
parser.add_argument("-maxplent", "--maxpercenttolent", help="Max percent to lent. if set to 0 the bot will lent the 100%.")
```

![screenshot - 100416 - 22 22 49](https://cloud.githubusercontent.com/assets/18429660/19099212/4aa0d9aa-8a82-11e6-8bf3-f06ea6cac9f4.png)
in the screenshot shows more than 100% on lendable because I set the limit and the coins was lend.

the default is 100%

[https://github.com/prfiredragon/poloniexlendingbot/blob/max-to-lent/lendingbot.py](url)
[https://github.com/prfiredragon/poloniexlendingbot/blob/max-to-lent/www/lendingbot.js](url)
You can check the code  and ask any changes you think that I can made. 
When is ready I submit the pull request.

**Comment by Evanito** [comment]
Hey @prfiredragon! Thank you for helping to add a feature!
Don't be hesitant to create a pull request with any code changes you have, it allows us to make comments, requests, and approvals much easier than on a separate blob. And either way, it is better all conversation about a code change be on the relevant PR.
