### ISSUE TITLE
webserver ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by neomvll** [Mikadily/poloniexlendingbot#118]
Hi guys,
I have a RPi running bot, but if I try access http://xxx.xxx.xxx.xxx:8000/lendingbot.html from any other device, I got ERR_CONNECTION_REFUSED
I have others apps with webservers running in others ports very well, but I can't open the bot page.
Bot webserver is running:
"Started WebServer, lendingbot status available at http://127.0.0.1:8000/lendingbot.html"
Ty for the great job

**Comment by Evanito** [comment]
On line 420 of lendingbot.py, set the host to: 0.0.0.0

Then you will be able to access the page by `<your RPi's local ip>:8000/lendingbot.html`

**Comment by neomvll** [comment]
Thank you a lot.
I think it can be put on config file too :)
