### ISSUE TITLE
Its time to talk GUI

### ISSUE THREAD

**Issue by Evanito** [Mikadily/poloniexlendingbot#120]
I am looking at [Kivy](https://kivy.org/#home)

The bot is currently very "homebrew" style and requires a certain (although small) amount of coding and configuration knowledge.

Creating a GUI can smooth usage of the process, create interactive configuration of the bot (less goof ups because of missing a space somewhere) and make it easier for a commonplace person to use.

Is this something we should put on our roadmap?

**Comment by rnevet** [comment]
IMO a config file is sufficient, the bot can be run on servers without UI as well (like I actually do).
