### ISSUE TITLE
Change server HOST to default IP

### ISSUE THREAD

**Issue by Evanito** [Mikadily/poloniexlendingbot#122]
Currently, if a user wants to access the webserver from another computer they need to navigate in lendingbot.py to the line where it says `HOST = "127.0.0.1"` and change it to `HOST = "0.0.0.0"`

Suggestion: Change this value to `0.0.0.0` by default

It makes the page accessible by localhost(aka `127.0.0.1`) AS WELL AS enabling routing to the page from another computer or router via the computer's local IP address.

I can't think of a reason not to do this.

**Comment by rnevet** [comment]
127.0.0.1 is traditionally localhost, and that's why I chose it.
I agree there is no reason why no to change the default value.
I would however say the solution is actually to have HOST and PORT as configuration options.

**Comment by Evanito** [comment]
@rnevet I will change my PR to do so. It is better to give the users choice.

It will be done in a few days when I have some free time.
