### ISSUE TITLE
Fails to run if jsonfile and jsonsize not set

### ISSUE THREAD

**Issue by wolfmankurd** [Mikadily/poloniexlendingbot#134]
Fails with error:
````
Obtaining settings from config file.
Traceback (most recent call last):
  File "lendingbot.py", line 235, in <module>
    log = Logger()
  File "/home/ali/Workspace/poloniexlendingbot/Logger.py", line 85, in __init__
    self.refreshStatus()
  File "/home/ali/Workspace/poloniexlendingbot/Logger.py", line 111, in refreshStatus
    self.console.status(self._lended, self.timestamp(), self._daysRemaining)
````

Issue is in Logger.py line 81 to 85, unfortunately JsonOutput() and ConsoleOutput() are not interchangable. Notably the status prototypes are mismatched; def status(self, status, time, days_remaining_msg) and     def status(self, msg, time='').

Logger.py line 81 to 85

        if json_file != '' and json_log_size != -1:
	    self.console = JsonOutput(json_file, json_log_size)
	else:
            self.console = ConsoleOutput()
        self.refreshStatus()

We come acropper here: Loggerpy Line 106

    def refreshStatus(self, lended='', days_remaining=''):
        if lended != '':
            self._lended = lended
	if days_remaining != '':
            self._daysRemaining = days_remaining
        self.console.status(self._lended, self.timestamp(), self._daysRemaining)

Interim solution is to uncomment jsonfile and jsonsize in default.cfg

**Comment by rnevet** [comment]
Hi,

Can you try changing https://github.com/Mikadily/poloniexlendingbot/blob/master/Logger.py#L22
to: 
`def status(self, msg, time='', days_remaining_msg=''):`

I think this was missed in recent change.

**Comment by wolfmankurd** [comment]
It works a treat.

**Comment by rnevet** [comment]
Great, I opened a PR with the fix.
