### ISSUE TITLE
sleeptimeinactive time suggest for pythonanywhere 

### ISSUE THREAD

**Issue by lollita** [Mikadily/poloniexlendingbot#139]
Whats high sleeptimeinactive time suggest to use for pythonanywhere website?

**Comment by Evanito** [comment]
@lollita It depends largely on how many coins you will be lending at once. I recommend starting with the default value of 300 seconds and checking if you are reaching the cap. 

If you are, increase it by a minute or so. If you aren't reaching the cap every day then you are probably good.

**Comment by Evanito** [comment]
It goes off of "max" cpu time. Meaning if the bot runs using only a little bit of cpu it wont use the maximum  of 1second per second. If it uses 10% cpu then it will only use .1 maxcpusecond per second.

Like I said, please experiment with your coins to see what sleeptime works.

**Comment by rnevet** [comment]
Please don't open issues for advice, we have a gitter chat where you can ask community members.
