### ISSUE TITLE
Feature Request: Enddate for lending

### ISSUE THREAD

**Issue by tuffig** [Mikadily/poloniexlendingbot#14]
Hi, can you please implement a enddate for lending? 
The bot should automatic decrease the lendingtime till the specific date is reached ( - 2 days min lending time)
So, for example, I can have on 01.05.2016 all coins available.

thx

**Comment by Mikadily** [comment]
Good one, I should implement it.

**Comment by Evanito** [comment]
If there are 40 days left until the deadline, but the bot wants to lend some high rate coins for 60 days, should it lend at 40 days or the 2 day default?

**Comment by rnevet** [comment]
I agree, should be 40 in that case.
