### ISSUE TITLE
Unkown error

### ISSUE THREAD

**Issue by tuffig** [Mikadily/poloniexlendingbot#15]
Today poloniex is under heavy loads, so errors occur and the script exits with "unknown error".
- ERROR: HTTP Error 502: Bad Gateway
- ERROR: HTTP Error 504: Gateway Time-out
- unknown error

Can you catch the error, so the script would not exit?

**Comment by Mikadily** [comment]
Technically it should catch all errors, print them and resume. Not sure why that is not working...

There's another branch https://github.com/Mikadily/poloniexlendingbot/tree/multithreading which is more robust, it never quits.
