### ISSUE TITLE
Failed to start WebServer[Errno 98]

### ISSUE THREAD

**Issue by sestoculo** [Mikadily/poloniexlendingbot#156]
I have a problem with web server. I try my best and follow instruction. I have used free account on pythonanywhere, but I am on dead end with this message:
Failed to start WebServer[Errno 98] Address already in use
I appreciate help.

**Comment by rnevet** [comment]
Basically it means the PORT is already in use, maybe you have some other app using the port (maybe the bot is already running?).  You can also change the Port in the config file.

**Comment by sestoculo** [comment]
![image](https://cloud.githubusercontent.com/assets/9396777/20859886/9502b8ac-b96b-11e6-9f91-4779d8a0f69a.png)
Actually pythonanywhere_com_wsgi.py is running with "hello world application" because I have choosen manual configuration of web site. How to stop this python app, and how to make configuration for web on pythonanywhere_com because I have above picture on static page:
Thanks in advance

**Comment by rnevet** [comment]
@sestoculo  I haven't used python anywhere, maybe ask on our Gitter? https://gitter.im/Mikadily/poloniexlendingbot

**Comment by Evanito** [comment]
The wsgi is just a config file... You do not even need to use it.
If you are following the instructions from https://poloniexlendingbot.readthedocs.io/en/latest/installation.html#creating-the-web-app-optional then you do not need to use the `startwebserver` option in the bot config.

**Comment by rnevet** [comment]
@sestoculo is the issue resolved?

**Comment by sestoculo** [comment]
no, I invest some time, but I did not resolve my problem. I have response of the web site like in picture above an I have message: "Failed to start WebServer[Errno 98] Address already in use". I am ok with that, I do not have web page about bot, but bot works good.

**Comment by laxdog** [comment]
I actually noticed this too, but haven't spent any time on it. 

It happens sometimes after you shut down the bot and restart it shortly after, it looks like it's not releasing the port properly. Though `netstat -tnlp` and `lsof` show no sign of it being used. 

If you leave it for a minute and restart, the error doesn't appear.
