### ISSUE TITLE
Loading JSON log is failing

### ISSUE THREAD

**Issue by chfast** [Mikadily/poloniexlendingbot#163]
The webpage always shows: `getJSON failed, status: parsererror, error: SyntaxError: Unexpected end of JSON input`.

**Comment by rnevet** [comment]
We'll need more info about your setup. Was it working before?

**Comment by chfast** [comment]
I think it stopped working with version 0.3, but I ignored the problem back then. Today I was upgrading to master to check if anything has changed. I noticed that jsonfile option must be set (wasn't before). But in the end nothing has changed.
The JSON log is being updated (I can read contests in a terminal), but for some reason JavaScript is failing loading it. I also validated the JSON externally and the syntax is correct.

**Comment by chfast** [comment]
Ehh... I visited `/botlog.json` in browser and now everything is working. Maybe it was some kind of browser cache issue, missing jsonfile option before.

Sorry.

**Comment by rnevet** [comment]
No problem, you can also try the gitter chat to get assistance in troubleshooting.

**Comment by Fabien98** [comment]
Hi,
I actually have the same problem with the webserver:
`getJSON failed, status: parsererror, error: SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data`
I noticed as well that I have no " botlog.json" in my www folder.
Do we need to create an empty one?

**Comment by rnevet** [comment]
No, the bot creates the file according to the setting in the config. Please share relevant config entries.

**Comment by Fabien98** [comment]
Thanks for your answer, I should have miss something since the .json file was not created when running the bot and the webserver:
Here's the relevant cfg entries:
```
#This option creates a json log file instead of console output which includes the most recent status.
#Uncomment both jsonfile and jsonlogsize to enable.
#Keep this in the default location if you want to use the webserver.
jsonfile = www/botlog.json

#Limits the amount of log lines to save.
jsonlogsize = 200

#Enables a webserver for the www folder, in order to easily use the lendingbot.html with the .json log.
startWebServer = true

```
I'm running the bot through PythonAnyWhere service

**Comment by rnevet** [comment]
I'm not sure if you should have the enableWebServer set to true, doesn't Python anywhere come with its own webserver? Did you check the docs for setup?

**Comment by rnevet** [comment]
In any case I suggest you either open a new issue with details on your setup problem or try asking for help on gitter.

**Comment by Fabien98** [comment]
Ok no need to open a new issue.
You were right, no need to set `startWebServer = true` on PythonAnyWhere
I reboot and everything runs fine now.
Thanks!
