### ISSUE TITLE
Great project!

### ISSUE THREAD

**Issue by obsesshub** [Mikadily/poloniexlendingbot#164]
Good-day Mikadily & everybody participating, I love this project, thank you so much!

Just to mentioned is there anyone here who maybe know how I might should do to offer hosting for my premium users? Yet I want to mention that this is some sort of gift for my premium users of the other values I have already given.

If you want to pass me to another board of discussion, feel free to do so!

The _out-of-scope_ area of were I am thinking is architecture wise of how it might be the best way, right now I use Firebase and ionic framework for mobile users. Yet I'm not a hardcore developer and some advises were my focus shall be at or anyone that knows _how to_ or knows _anyone_ that knows _how to_ are highly appreciated to wrap text down below!

Thank you so much for what you guys have already been giving to us and I wish you all a good Christmas!

/OH

**Comment by Evanito** [comment]
This is outside the scope of a Github issue.

If you are looking for casual discussion about the bot I may suggest you visit our Gitter chat: https://gitter.im/Mikadily/poloniexlendingbot
