### ISSUE TITLE
Feature Request: xx_daythreshold

### ISSUE THREAD

**Issue by tuffig** [Mikadily/poloniexlendingbot#17]
I find it useful, when there is more then only one treshold as for 60 days.
15, 30, 60 days would be fine.
Maybe, to be more flexible, you could use somethink like
daytreshold[15] = x
daytreshold[30] = y
daytreshold[60] = z
daytreshold[...] = ...
so any treshold can be used.

**Comment by Evanito** [comment]
Mostly answered with #108
