### ISSUE TITLE
OSError: [Errno 2] No such file or directory: ''

### ISSUE THREAD

**Issue by janhohner** [Mikadily/poloniexlendingbot#176]
Since this morning I get the following error on the current master:
> $ python lendingbot.py
Traceback (most recent call last):
  File "lendingbot.py", line 15, in <module>
    os.chdir(os.path.dirname(sys.argv[0]))  # Allow relative paths
OSError: [Errno 2] No such file or directory: ''

I wanted to also take this chance and say thank you for this useful software, it helps me a lot!

**Comment by Evanito** [comment]
Hello, thank you for submitting this issue.
A fix will be pushed very soon.
