### ISSUE TITLE
Required minloansize changed (Amount must be at least 0.01)

### ISSUE THREAD

**Issue by lexrms** [Mikadily/poloniexlendingbot#180]
Hi Guys,

Poloniex has changed the minimum loan amount of BTC (0.01), Clam (1.0) and other coins. This is causing an error in the BOT.

Thank you

**Comment by Evanito** [comment]
Oh great. Fix: change `minloansize` setting to 0.01 and I will get a fix out as soon as I can.
This is annoying that there was no notice.
Only thing we need to change is the default value, then the bot will work fine again.
```
BTC: 0.01 
BTS 0.01
CLAM 0.01
DOGE 0.01
DASH 0.01
LTC 0.01
etc...
```

**Comment by lexrms** [comment]
Hi Evanito,

BTC: 0.01
Clam: 1.0
BTS: 1.0

I dont tested another coins...

**Comment by rnevet** [comment]
Let's not rush a fix here, there is no problem configuring this. 
I'll send polo an email asking for clarification.

**Comment by Evanito** [comment]
@rnevet Definitely the best option, given that we have no documentation or communication to work with.

**Comment by rnevet** [comment]
Response from Poloniex:
'''
Hi Raanan,

The minimum loan amount should be 0.01 for all coins. Are you seeing something different?
'''

**Comment by Evanito** [comment]
Test minloansize of 0.01 and check if you get any errors

**Comment by lexrms** [comment]
I tested it manually at Poloniex. Clam coin amount 0.4
![poloniex](https://cloud.githubusercontent.com/assets/13912856/21861886/06756964-d81e-11e6-9df4-cbdc0884992e.png)

**Comment by Evanito** [comment]
Hmmm... what if the minimum is somehow tied to your account? I saw 0.01 on
that same screen, that is how I got those numbers above

**Comment by lexrms** [comment]
Maybe it's only for my account, but in this case it's a problem for other bot users if Poloniex uses different policies for each account.

**Comment by Evanito** [comment]
Would you mind creating a full list of your minimum loan sizes so I can
compare? @lexrms

On Wed, Jan 11, 2017, 11:01 lexrms <notifications@github.com> wrote:

Maybe it's only for my account, but in this case it's a problem for other
bot users if Poloniex uses different policies for each account.

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/Mikadily/poloniexlendingbot/issues/180#issuecomment-271961919>,
or mute the thread

**Comment by lexrms** [comment]
I just tested them all and is accepting the value of 0.01 now ...
Have they changed the policy for my account maybe?
Could this be a problem in the future?

**Comment by rnevet** [comment]
@lexrms I've requested further Poloniex feedback to the issue. 

In any case the bot is limited to what the API allows it and we can only do our best, so it could be a problem in the future but it's good that it isn't a problem now. :)

@Evanito In any case we need to update the minloansize lower limit to 0.01 (my personal config value is set to 0.1)

**Comment by rnevet** [comment]
Update from Poloniex:
"
My bad, it would appear that certain coins do have special limits. I'm seeing the following:

FCT - 0.1
DOGE - 5
BTS - 1
CLAM - 1
BTC - 0.01
DASH - 0.01
LTC - 0.01
XMR - 0.01
ETH - 0.01
MAID - 0.01
STR - 0.01
XRP - 0.1

Please note the minimum loan sizes are not part of the API spec and therefore could be subject to change in the future. We try to minimize changes as much as possible, though.
"

**Comment by Evanito** [comment]
Okay, I can make the `minloansize` into a dictionary with settings for each coin, then grab the min like we currently do with the coincfg.

**Comment by lexrms** [comment]
I tested again and I think they changed again during the day. Rnevet is correct.

**Comment by rnevet** [comment]
@Evanito I asked Poloniex if it would be possible to get the list of coins and their min loan size from the API.  

In any case I would not like to have the minloansize as a dictionary in the config, too complex.
I would suggest we drop the hard requirement for a correct minloansize and just check it at runtime vs the api limit - if the minloansize is lower, use api limit and optionally print a warning.

**Comment by laxdog** [comment]
The config is already getting pretty messy to be honest, that said, it would be quite nice to be able to configure minimum separately.

I've quite a few different balances and think it would be pretty useful if they were all split into separate ConfigParser sections. Though I'm not sure how many others would use it. Something like:
```
[BTC]
minloansize =
mindailyrate = 
maxactiveamount = 
maxtolend = 
maxpercenttolend = 
maxtolendrate =
```

I'd be happy to have a look and try to make a PR if there's interest. 

Anyway, this should almost definitely be hardcoded if it's not available from the polo API. It might be useful to Class or Module level variables in modules/Poloniex.py. Then they could be easily changed later especially if they introduce an API call for it down the line.

**Comment by Evanito** [comment]
Hmm. What about parsing the error message on startup to construct the min

**Comment by rnevet** [comment]
You won't get an error necessarily, it is more of an error handling.

**Comment by Evanito** [comment]
I mean purposefully creating too small lends, then parse `Error: Amount must be at least X.` to find min size X for each coin.

**Comment by Evanito** [comment]
I found a fix that I think works flawlessly. Use the config setting as a default, but update it to the API error message if it gets one. Does not interfere with any other exceptions.
Only on the lending-rewrite branch, it is good to run right now.

**Comment by ChrisG2711** [comment]
Thanks for the fix, works fine!
As a background to this: a moderator in Polo chat stated that the change of min amount was made to prevent "lending spam" that led to polo api isssues.

**Comment by misovan** [comment]
Hi, I'm new to discussion, but considering that relative values of lendable currencies are different by multiple orders, I would suggest to have the minloansize configurable by currency. 
I tweaked the code in my local bot by extending current per-currency configuration by optional minloansize value, taking global value if not set. Do not think it adds too much complexity (small tweak in Configuration.get_coin_cfg() and in Lending.create_lend_offer()).
To move things a little more conceptually, I like laxdog's idea described above - to have clean default settings that one can overrride in per-currency config sections.

**Comment by laxdog** [comment]
I've got a patch to do the config per coin without the minloan size. I'll hopefully get that sorted out tonight and then submit the PR, I wasn't sure what to do with as @Evanito has commits that aren't merged from the lending-rewrite branch. 

Sorry, I'm pretty new to working with github and don't get the full work flow. Should I be working from that branch to add this?

**Comment by rnevet** [comment]
we usually work from master but in this case, I would suggest you work off lending-rewrite.

**Comment by laxdog** [comment]
Still need to test it and update any docs, but there's a PR at https://github.com/Mikadily/poloniexlendingbot/pull/190 in case anyone else wants to have a look at it. Might be a day or two before I can look at this again. I don't think it's a rush until that is getting merged with master anyway. 

It allows config as I suggested above for each coin and allows you to use a minloansize on a per coin basis.

**Comment by rnevet** [comment]
Nice.
