### ISSUE TITLE
__init__() takes exactly 6 arguments (2 given)

### ISSUE THREAD

**Issue by utdrmac** [Mikadily/poloniexlendingbot#181]
Hello. Just installed this today. Had to upgrade my numpy to latest version to fix a previous error. After about 10-20minutes, I got this error.

```
Welcome to Poloniex Lending Bot
Started WebServer, lendingbot status available at http://10.10.10.202:8000/lendingbot.html
2017-01-11 15:29:16 Error: __init__() takes exactly 6 arguments (2 given)
Traceback (most recent call last):
  File "lendingbot.py", line 68, in <module>
    Lending.cancel_all()
  File "/usr/src/poloniexlendingbot/modules/Lending.py", line 100, in cancel_all
    loan_offers = api.return_open_loan_offers()
  File "/usr/src/poloniexlendingbot/modules/Poloniex.py", line 129, in return_open_loan_offers
    loan_offers = self.api_query('returnOpenLoanOffers')
  File "/usr/src/poloniexlendingbot/modules/Poloniex.py", line 86, in api_query
    raise type(ex), type(ex)(ex.message + ' Requesting %s' % command), sys.exc_info()[2]
TypeError: __init__() takes exactly 6 arguments (2 given)

Unhandled error, please open a Github issue so we can fix it!
```

**Comment by rnevet** [comment]
Which Python version are you using?

**Comment by utdrmac** [comment]
```
root@gasgiant:/usr/src/poloniexlendingbot# python --version
Python 2.7.9
```

**Comment by rnevet** [comment]
Thanks for the report, there seem to be an error in the actual error handling which is hiding a failed call to returnOpenLoanOffers.  
In any case this shouldn't stop the bot from working, it will just retry after a delay.

Is the bot otherwise running?

**Comment by utdrmac** [comment]
Seems to be running otherwise.

**Comment by rnevet** [comment]
This error was already noticed here
https://github.com/Mikadily/poloniexlendingbot/issues/175

**Comment by rnevet** [comment]
Research Update:
I think the error comes from my attempt to rethrow the Exception in line 86:
`raise type(ex), type(ex)(ex.message + ' Requesting %s' % command), sys.exc_info()[2]`

It assumes that type(ex) is an exception type that accepts a message to initialize.

**Comment by Evanito** [comment]
Not fixed by #174 in this state, considering removing commits dealing with error handling.

**Comment by laxdog** [comment]
@rnevet Since you already have the exception, instead of raising a new one, you could:

```
ex.message = "{0} Requesting {1}".format(str(ex), command)
raise
```

Then change all the str(ex) in lendingbot.py to ex.message.

message will always exist for python Exceptions and you'd be creating it for any random ones that are caught that somehow might not have it. Though they always should. 

Or of course, just ignore the original type and raise a new one.

**Comment by rnevet** [comment]
@laxdog 
The `ex.message` solution is a good idea, can you make the PR?
