### ISSUE TITLE
percentile() got an unexpected keyword argument 'interpolation'

### ISSUE THREAD

**Issue by ChrisG2711** [Mikadily/poloniexlendingbot#184]
Hi,
this my very first try working with my raspberry pi updated with all packages. 
I get this when starting the script

Started WebServer, lendingbot status available at http://localhost:8000/lendingbot.html
2017-01-13 19:25:26 Error: percentile() got an unexpected keyword argument 'interpolation'
Traceback (most recent call last):
  File "lendingbot.py", line 69, in <module>
    Lending.lend_all()
  File "/home/pi/poloniexlendingbot/modules/Lending.py", line 141, in lend_all
    usable_currencies += lend_cur(cur, total_lended, lending_balances)
  File "/home/pi/poloniexlendingbot/modules/Lending.py", line 163, in lend_cur
    recommended_min = Analysis.get_rate_suggestion(active_cur)
  File "/home/pi/poloniexlendingbot/modules/MarketAnalysis.py", line 118, in get_rate_suggestion
    result = numpy.percentile(rates, int(percentile), interpolation='linear')
TypeError: percentile() got an unexpected keyword argument 'interpolation'

Unhandled error, please open a Github issue so we can fix it!
2017-01-13 19:35:28 Error: percentile() got an unexpected keyword argument 'interpolation'
Traceback (most recent call last):
  File "lendingbot.py", line 69, in <module>
    Lending.lend_all()
  File "/home/pi/poloniexlendingbot/modules/Lending.py", line 141, in lend_all
    usable_currencies += lend_cur(cur, total_lended, lending_balances)
  File "/home/pi/poloniexlendingbot/modules/Lending.py", line 163, in lend_cur
    recommended_min = Analysis.get_rate_suggestion(active_cur)
  File "/home/pi/poloniexlendingbot/modules/MarketAnalysis.py", line 118, in get_rate_suggestion
    result = numpy.percentile(rates, int(percentile), interpolation='linear')
TypeError: percentile() got an unexpected keyword argument 'interpolation'

Unhandled error, please open a Github issue so we can fix it!

Regards
chris

**Comment by dshopov** [comment]
Hello ChrisG2711,

Raspbian repository have old version of python-numpy.
You have 3 options:
1. Remove the package and install the newer version via pip
2. Just remove the package and rely on "manual percentile method". Bot will complain but will work.
3. Comment out all Market Analysis lines in your config and it will work without it

Regards,
Dimitar

**Comment by ChrisG2711** [comment]
Hello Dimitar,

thank you very much for the solution!

Raspberry did not let me remove the package but "sudo pip install numpy --upgrade" seems to have done the trick. Running into a new error now unfortunately asking for reporting, will open a new issue for that. 
Thanks again and have a great weekend!

Regards
Chris

**Comment by mikemr** [comment]
hello, what version of numpy is required ? I am running on cent os 7 and numpy-1.7.1

**Comment by Evanito** [comment]
@mikemr Hey mike, what output do you get when you run `sudo pip install numpy --upgrade`?

**Comment by mikemr** [comment]
pip is not found on the vps I am using. I installed using - sudo yum install numpy

**Comment by mikemr** [comment]
sudo yum upgrade numpy
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.cisp.com
 * epel: mirror.steadfast.net
 * extras: mirrors.gigenet.com
 * updates: mirror.eboundhost.com
No packages marked for update

**Comment by Evanito** [comment]
@mikemr  I believe a working alternative is `sudo apt-get install python-numpy` if you have access to that
