### ISSUE TITLE
API request rate limit.

### ISSUE THREAD

**Issue by Evanito** [Mikadily/poloniexlendingbot#188]
Apply a rate limit for api requests that only allows a maximum of 6 requests to be sent per second, so as to not go over Poloniex's limit.

Related issue: #167

**Comment by rnevet** [comment]
We should Integrate the couch from:
https://github.com/s4w3d0ff/python-poloniex/blob/master/poloniex/coach.py

Almost as is, just init and call wait before each api call - should be quite straight forward.

**Comment by rnevet** [comment]
I'll make an attempt to implement this.

**Comment by Evanito** [comment]
Fixed by #189
