### ISSUE TITLE
Maximum call rate

### ISSUE THREAD

**Issue by songproducer** [Mikadily/poloniexlendingbot#19]
Hi,

Poloniex is limited to 180 calls per minute. Are there any other calls to Poloniex placed (not counting cancelling calls) like checking other peoples' loan rates?

**Comment by Mikadily** [comment]
Oh, there's many different calls. Where did you get this (180 limit)?

**Comment by Mikadily** [comment]
Ok found it: "Please note that any public method call beyond the 180th in the space of one minute will be met with silence."

Shouldn't be a problem, not many public calls being used.

**Comment by songproducer** [comment]
How low can I set the sleep? I have it set to 17.

**Comment by Mikadily** [comment]
Minimum is 1. But I don't think it's beneficial. You should watch the log and don't set sleeptime lower than it takes to cancel and put new loans. That's my take.
