### ISSUE TITLE
Traceback Error 123

### ISSUE THREAD

**Issue by keatond** [Mikadily/poloniexlendingbot#192]
Hey! Thank you so much for building this project.  It has helped a ton with setting up my lending. I came across this issue when trying to run the program today. It has been working great up until this point. Not sure what has changed.

Traceback (most recent call last):
  File "lendingbot.py", line 18, in <module>
    os.chdir(os.path.dirname(sys.argv[0]))  # Allow relative paths
WindowsError: [Error 123] The filename, directory name, or volume label syntax is incorrect: ''

**Comment by laxdog** [comment]
Can you provide the command line you used to start it and the full path of the directory you were in at the time?

I suspect it's something to do with special characters.

**Comment by keatond** [comment]
Hey Laxdog,

Thanks for replying!

The directory location is: C:\Users\keato\Desktop\Bitcoin\poloniexlendingbot

I have Git and python 2.7.10 installed. Also made sure that python had PATH.

The steps i take are:
1. open cmd
2. cd to directory above
3. type: python lendingbot.py

Not sure what I could be doing wrong.

Thanks for looking into this!

**Comment by rnevet** [comment]
Do you have the "default.cfg.example" file in the bot folder?
I think this error can happen if it is removed.

**Comment by keatond** [comment]
You guys are a life saver. So I have figured it out.

In the installation instructions it says:
To configure the bot with your settings:

Copy default.cfg.example to default.cfg
Open default.cfg and enter your desired settings (information on settings here).
Save default.cfg

Which I thought that meant once you are done with "default.cfg.example" it could be removed. I was very incorrect. Downloaded a new version to another folder and threw the example file into the original folder and everything started back up. 

Thanks again for all the help in trouble shooting!

**Comment by rnevet** [comment]
@Evanito
 Trying to read 'default.cfg.example' to determine if to do a chdir causes this issue if you remove the file. Can we find a better solution?

**Comment by Evanito** [comment]
Sure, I can just open any file, including the running file itself.
