### ISSUE TITLE
Custom mindailyrate not working.

### ISSUE THREAD

**Issue by NeuralMiner** [Mikadily/poloniexlendingbot#195]
On `lending-rewrite` branch, bot is not respecting custom coin config:

> 2017-01-19 17:15:53 Placing 6.11105483 MAID at 0.34989% for 2 days... Loan order placed.
> 2017-01-19 17:15:52 Using custom mindailyrate 0.400% for MAID

Latest `lending-rewrite` (2c3e4c5130a913808c5deb3aeae59079beb86a1d)
Debian 8
Python 2.7.9

**Comment by rnevet** [comment]
Committed a fix into lending-rewrite https://github.com/Mikadily/poloniexlendingbot/pull/174/commits/bdc87cc3bc51d9fb8344a10f90b959e0187c5c21 , min_daily_rate wasn't correctly checked.

**Comment by NeuralMiner** [comment]
Testing `lending-rewrite` bdc87cc3bc51d9fb8344a10f90b959e0187c5c21 now so see if minrate is working.
When launching the latest, I'm getting this in the console: 
> Currency USDT is not valid, choose a valid currency from here: https://blockchain.info/api/exchange_rates_api

I have the output currency set to USDT from the default BTC:

`outputCurrency = USDT`

**Comment by rnevet** [comment]
Seems there is a bug with USDT in this branch (related to trying to support more currencies), could you still verify the min_daily_rate?

**Comment by rnevet** [comment]
USDT issue should be fixed https://github.com/Mikadily/poloniexlendingbot/pull/174/commits/3e3b17a59df89bda0d082969a38703faceeb079b.

**Comment by NeuralMiner** [comment]
Awesome, min_daily_rate is now working correctly as well as USDT (on 3e3b17a).
Looks like setting maxactive to 0 isn't working:
2017-01-21 19:09:25 Placing 1.10227752 CLAM at 0.0455% for 2 days... Loan order placed.
2017-01-21 19:09:24 maxactive amount for CLAM set to 0, won't lend.

coinconfig = ["MAID:0.2:1:0:0:0","CLAM:0.05:0:0:0:0"]

**Comment by Evanito** [comment]
@NeuralMiner Should be fixed in https://github.com/Mikadily/poloniexlendingbot/pull/174/commits/a2f14e451866ea7b70f1cfa46fbc0201b87ecf12

**Comment by NeuralMiner** [comment]
Confirmed working correctly on a2f14e4. Thanks.

**Comment by laxdog** [comment]
Sorry, I broke that!
