### ISSUE TITLE
Only Bitcoin, Not USD Value. More Of A Comment.

### ISSUE THREAD

**Issue by Linrono** [Mikadily/poloniexlendingbot#196]
I had set up my bot to show the estimated value of my returns in USD and this seemed to work when I was lending multiple cryptocurrencies. I recently was looking at it while purposely only lending Bitcoin and my returns were only in Bitcoin. I don't know if this is by design but I personally would like to see my returns calculated into USD even when just Bitcoin lending if I so choose.

**Comment by Evanito** [comment]
Try USDT

**Comment by rnevet** [comment]
Actually this is a side effect of an older design decision, not to display the summery if only one coin is lent - this was before the summery had the extra functionality. 

https://github.com/Mikadily/poloniexlendingbot/blob/master/www/lendingbot.js#L150

**Comment by Linrono** [comment]
Okay, so it is on purpose. Well, again, I would like to see it but I'm happy as a CLAM without it... 

Sorry. I actually looked that up and made sure that was a saying and that I wasn't crazy. Thank you guys for all your hard work.

**Comment by Linrono** [comment]
I actually just went into the JS file and changed the if statement into 
if (currencies.length > 1 || Coin != "BTC") {
And this seems to give me the functionality I was looking for. 
Thanks for showing me where that was in the code.

**Comment by noonway** [comment]
I'd like to see this get into the official version as well.  I have added it to my version also as I always only lend BTC and want to see USDT.

**Comment by Evanito** [comment]
If you have a fix that you think would work in general for the bot, feel free to create a pull request with your changes.

**Comment by rnevet** [comment]
I think I have an idea. ;)  

Basically, every coin displays it's own earnings and BTC in it's own line, that's why when we didn't have conversions and had only one coin the summery line was redundant.

I'll change it that if there is a conversion of the summary from BTC to another currency it will be displayed anyway.

**Comment by noonway** [comment]
That's a much better idea than the hardcode coin != BTC... Make it so, rnevet! 👍

**Comment by rnevet** [comment]
Actually, the solution is to hardcode Coin != BTC, exactly like you did...

Coin is the summary coin (badly named) and the change you did should cover all other cases as well. 👍
