### ISSUE TITLE
Being able to show bitcoin value in mBTC or bits. 

### ISSUE THREAD

**Issue by tuberculo** [Mikadily/poloniexlendingbot#197]
As bitcoin value is relatively high, the amount in bitcoin someone posses tends to be a low value. To me, using all those decimal places is very unnatural, so I prefer to see the amounts in bits (µBTC). 
I suggest an option to show the amount of bitcoin in mBTC or bits, as the user prefers.

**Comment by Evanito** [comment]
Shouldn't be too complicated with #149's existing functionality.
@rnevet?

**Comment by rnevet** [comment]
Should be easy enough to add as a Get parameter to the page.

**Comment by rnevet** [comment]
@tuberculo you can test the implementation on https://github.com/Mikadily/poloniexlendingbot/tree/custom_btc_display_unit
branch

**Comment by rnevet** [comment]
Implemented and merged.

**Comment by tuberculo** [comment]
I tested and it is working great. Thanks.
But I think that the total lent should also be in the selected unit.

**Comment by rnevet** [comment]
Good point.
