### ISSUE TITLE
Custom mindailyrate per coin is ignored

### ISSUE THREAD

**Issue by tom111** [Mikadily/poloniexlendingbot#208]
In the current master 6906f25a6 I have the following issue:

I have set a global mindailyrate of 0.0219.  My coinconfig contains this:

coinconfig=[...,"DASH:0.0239:1:0:0:0",...]

The output of the bot is right, but the minimum lending rate is wrong:

2017-02-01 09:48:03 Using custom mindailyrate 0.023900% for DASH
2017-02-01 09:48:04 Placing XX.XX DASH at 0.0218% for 2 days... Loan order placed.

This bug seems to occur only if the value in coinconfig is higher than the global value.

**Comment by rnevet** [comment]
It looks like the cur_min_daily_rate isn't used which means also the Analytics data is ignored. 
https://github.com/Mikadily/poloniexlendingbot/blob/master/modules/Lending.py#L246

Needs fixing.

**Comment by rnevet** [comment]
@Evanito 
Could be that in this line https://github.com/Mikadily/poloniexlendingbot/blob/master/modules/Lending.py#L293 the value should be set to cur_min_daily_rate ?

**Comment by Evanito** [comment]
@rnevet 
You are correct

**Comment by tom111** [comment]
Seems to be fixed. Thanks!
