### ISSUE TITLE
spreadLend only works for Bitcoin

### ISSUE THREAD

**Issue by songproducer** [Mikadily/poloniexlendingbot#21]
Currently my other coin gets lent out all in one loan.

**Comment by Mikadily** [comment]
I think you might not have enough coins to spread. Try changing gaptop to lower values, for proof.

**Comment by songproducer** [comment]
I definitely have more than enough coins to spread (5 digits). I changed gaptop to as low as 20 but no luck.

**Comment by Mikadily** [comment]
Absolute number of coins doesn't matter. What matters is relative number to the order book. Say you have 200k doge, but if the top order in book is 300k, there's not enough to spread (with your config).

Sorry. Try raising gaptop to 200, 500, 1000 and more.

**Comment by songproducer** [comment]
Thanks! Raising the gaptop did the trick :)
