### ISSUE TITLE
Not lending due to low rate even though rate is above mindailyrate.

### ISSUE THREAD

**Issue by NeuralMiner** [Mikadily/poloniexlendingbot#212]
```
2017-02-01 21:26:32 Not lending MAID due to low rate.
2017-02-01 21:26:31 Using custom mindailyrate 0.0700% for MAID
```
Current rate: 0.1982%

On `master` https://github.com/Mikadily/poloniexlendingbot/commit/f6fec7a3172bfb42d0131ba97fc0dac6cbab51e8

Edit:
Also not lending with custom coin config rate disabled and mindailyrate set to .02:

> mindailyrate = 0.02

> #coinconfig = ["MAID:0.07:1:0:0:0","CLAM:0.05:0:0:0:0"]

**Comment by rnevet** [comment]
You have Market analysis enabled and Maid had recently much higher rates - check the configuration..

**Comment by NeuralMiner** [comment]
Sure enough. Thanks.

**Comment by rnevet** [comment]
I think we should add the min rate used to decide not to lend to the log line.
