### ISSUE TITLE
Webserver display error in Doge 

### ISSUE THREAD

**Issue by lexrms** [Mikadily/poloniexlendingbot#236]
Guys,

I think I found a small error in webserver doge printing:

![20170217 doge bug](https://cloud.githubusercontent.com/assets/13912856/23054473/3dd2814c-f4c7-11e6-9295-444a338c4483.png)

**Comment by rnevet** [comment]
It seems that the prettyFloat function works until the accuracy of e-7. 
Not a nice display of 0.00000019

**Comment by rnevet** [comment]
@lexrms this should be fixed on master now.
