### ISSUE TITLE
Market Analysis Stuck

### ISSUE THREAD

**Issue by rnevet** [Mikadily/poloniexlendingbot#248]
I've noticed that the Market Analysis fails to update the values in the files after sometime leading to estimated values being wrong. :(

Looking into the files, it is visible that the last information is some days old.

**Comment by utdrmac** [comment]
Oh yea. I have to remove historical files and restart the bot on a semi-regular basis in order to keep with "current" rates.

**Comment by laxdog** [comment]
I've started adding tests around these files, so I'll put something in for this to see if I can find anything.

**Comment by rnevet** [comment]
Should be fixed with latest merge.
