### ISSUE TITLE
Error in MarketAnalysis: new-line character seen in unquoted field

### ISSUE THREAD

**Issue by Fabien98** [Mikadily/poloniexlendingbot#254]
In order to solve the #216 error (see #226 as well)
"IndexError: list index out of range"

I manually cleaned up some csv files in my "market_data" folder.
(there was a blank line in one file (?))

However after a reboot, I encountered this error:
`Error in MarketAnalysis: new-line character seen in unquoted field - do you need to open the file in universal-newline mode?`

After some [research](https://slaptijack.com/programming/python-csv-error-on-new-line-character-in-unquoted-field/), I would suggest a pull in the modules/MarketAnalysis.py module:

use  "open_files[cur], 'rU'" insted of "open_files[cur], 'r'"

line97/98
```
            with open(open_files[cur], 'rU') as f:
                reader = csv.reader(f)
```
but since i'm just learning Python, let me know if it's relevant...

Thanks

**Comment by rnevet** [comment]
"I manually cleaned up some csv files in my "market_data" folder" - why not just delete them?
I'm assuming that your editor introduced some new-line chars that made the error you faced.

**Comment by Fabien98** [comment]
Here  the first 4 lines of one of my "COIN_market_data.csv":

```
2017-03-10 11:48:02,0.00006800

2017-01-31 22:37:07,0.00133700
2017-01-31 22:38:07,0.00133700
```

I deleted the first 2 lines.
I didn't delete the whole file because I didn't want to lose the whole market data history.

I edited the .csv file directly in PythonAnywhere.
I did this operation once in a text editor and it solved the bug previously..

**Comment by rnevet** [comment]
I still think that it a text editor issue, did your suggested code change help?

**Comment by Fabien98** [comment]
Yes, in my opinion as well,  it's definitely a text editor issue.
However I deactivated Market Analysis so I can't test the code change right now...

My code change suggestion might  make the "open" command more resilient to text editor
(but it may break some other stuff..)

Feel free to close this issue since a simple market data "wipe off" resolve this problem.

**Comment by rnevet** [comment]
Thanks for the update!
