### ISSUE TITLE
Market analysis takes the lowest market rate and does not ignore dust orders

### ISSUE THREAD

**Issue by fireburndread** [Mikadily/poloniexlendingbot#256]
Market analysis takes the lowest market rate and does not ignore dust orders
Seemingly it keeps the BTC popping up dust lending orders at 0.01xxxx but just less than 0.1 bitcoins above that, people are lending at 0.09

see attached
![that one idiot at 0 0199](https://cloud.githubusercontent.com/assets/26077594/23830787/ba90adec-074d-11e7-822a-91e6037d8bca.jpg)

**Comment by fireburndread** [comment]
also, really can't figure out what a percentage of YOUR balance means. Could the explanations add a practical example for ease of understanding?

**Comment by rnevet** [comment]
I can confirm some weird market analysis behavior - I'll look into that. 

Didn't get your 2nd comment is it related to the issue?

**Comment by fireburndread** [comment]
Thanks for the updates. I've been having issues putting the gapbottom and gaptop functions into practical application. Pasting the instructions here for reference:

- gapbottom is how far into the lending book (in percent of YOUR balance for the respective coin) the bot will go to start spreading lends...
--  10% gapbottom is recommended to skip past dust at the bottom of the lending book, but if you have a VERY high volume this will cause issues as you stray to far away from the most competitive bid. 

- gaptop is how far into the lending book (in percent of YOUR balance for the respective coin) the bot will go to stop spreading lends.
--  This value should be adjusted based on your coin volume to avoid going astronomically far away from a realistic rate.

Writing out a practical scenario of what it might have been programmed to function:
1. A man has 3 BTC. 1 in exchange, 1 in margin, and 1 in Lending.
2. Transfer is set as off.
3. The bot takes the 1 BTC as lending as the "balance"
4. gapbottom is set at 10, gaptop is set at 200
5. The bot calculated values for gapbottom and gaptop are 0.1 BTC and 2 BTC respectively
6. The 'spreadlend' is set at 3
7. The bot ignores the first 0.1 BTC. In the above sceenshot, it would have ignored the first two offers. The effective calculated gapbottom loan rate is now 0.100000%
8. The bot looks for the gaptop. As the gaptop value is 2 BTC, it deducts alls the loans from the bottom up, to reach the 2 BTC mark. In the above screenshot, because someone is trying to lend 22 BTC at 0.1000, the 2 BTC mark would be calculated as 0.100000%
9. The spreadloans take effect. As the gapbottom and gaptop values are 0.100000%, the three loans are placed at 0.100000%

Does that sound about right?

**Comment by rnevet** [comment]
Yes, that's sounds right.
Therefore my config values are:
gapbottom = 100
gaptop = 3000

**Comment by rnevet** [comment]
@fireburndread can we close this issue?
