### ISSUE TITLE
HTTP Error 422

### ISSUE THREAD

**Issue by Greveyaro** [Mikadily/poloniexlendingbot#257]
![screen shot 2017-03-12 at 16 13 51](https://cloud.githubusercontent.com/assets/18435422/23851260/2c3c2e5e-07e3-11e7-9f64-b7cc9af9a67f.jpg)

**Comment by laxdog** [comment]
I can't actually see your screen shot, I'm not sure if the upload failed or something. 

Can you just copy and paste the output from the terminal?

**Comment by Greveyaro** [comment]
![screen shot 2017-03-13 at 17 50 10](https://cloud.githubusercontent.com/assets/18435422/23865316/92de5650-0815-11e7-983d-9229a909f937.jpg)

**Comment by laxdog** [comment]
So the first one the 422, I haven't seen before, though it just looks to be problem connecting to Poloniex. It's not anything to worry about, but should probably be handled more gracefully by the bot. 

The second one (502: Bad Gateway) already has been fixed in the way I've mention, so you could do a pull on your repo to update and get the latest code.

**Comment by rnevet** [comment]
I think we can handle all HTTP Errors without printing exceptions, error messages are enough.

**Comment by laxdog** [comment]
Agreed, we can probably just change that line I put in the other day to look for 'HTTP Error' instead of 'HTTP Error 5'. 

I can raise a PR in the morning.

**Comment by rnevet** [comment]
Or we can test for instance of httperror

**Comment by laxdog** [comment]
Yip, OK.

**Comment by rnevet** [comment]
Actually we can catch instance of URLError also covering #251

**Comment by laxdog** [comment]
Opened https://github.com/Mikadily/poloniexlendingbot/pull/260

Missed this comment, so that's not in. I'll do it now though.

**Comment by laxdog** [comment]
OK, both are in now.

**Comment by Greveyaro** [comment]
![screen shot 2017-03-14 at 11 49 31](https://cloud.githubusercontent.com/assets/18435422/23897172/5733b7b6-08ac-11e7-9e17-5dd6eb6fef12.jpg)
