### ISSUE TITLE
DIscussion: Stats collection

### ISSUE THREAD

**Issue by laxdog** [Mikadily/poloniexlendingbot#259]
I've been thinking about ways to analyse what the best config options and strategies are. 

It's hard to do any back testing as loans aren't really the same as trading actual coins, so I thought it might be an idea to have an anonymous opt in stats collection setup where users could send data back to a google doc or something. 

We would create a new sheet every time the bot starts that recorded all the config settings, then it would update with each of the loans that were made including profit etc.

We can work out a way to parse the data later, we'd just need to start collecting the stats.

**Comment by rnevet** [comment]
I was thinking the same, issue with collecting stats is that it is very open for manipulation...

**Comment by laxdog** [comment]
Yea, though I'm not sure there's any way around that. If you wanted to send fudged data it would be really easy. 

We'd just have to take an average of the results received or something. 

Was just an idea, I'm struggling to come up with a good way to test this stuff.

**Comment by laxdog** [comment]
Closing this as it's unlikely to be a a good idea. 

Though as a foot note, I was considering setting up a channel on slack or something where trusted parties could post said info. That or adding support for gitter and doing the same there.
