### ISSUE TITLE
Pythonanywhere: Error: Failed to find the exchange rate for outputCurrency USD

### ISSUE THREAD

**Issue by SearchAndDestroy** [Mikadily/poloniexlendingbot#262]
I followed the guide and used Pythonanywhere and the bot is working great.
I changed the output currency to USD and I get this error:
Error: Failed to find the exchange rate for outputCurrency USD

I use the exact same default.cfg locally and it's working perfectly
Any idea why I am getting this?
Thanks

**Comment by kryztoval** [comment]
Are you sure you are not using USDT locally? Because poloniex has USDT but not USD.

**Comment by SearchAndDestroy** [comment]
Yes I am sure. I just checked

**Comment by kryztoval** [comment]
I have never been able to make it work for USD, only USDT. :O

**Comment by rnevet** [comment]
Might be a problem between Pythonanywhere server and https://blockchain.info

**Comment by rnevet** [comment]
The Bot is basically querying https://blockchain.info/tobtc?currency=USD&value=1 url for the conversion value - the error means it failed to get a valid response.

**Comment by rnevet** [comment]
Might be that you are sharing an IP with other computers querying the service and are going over the quota...

**Comment by kryztoval** [comment]
If you use USDT the value should be really close though. USDT evaluates to exactly USD. At least in theory.

**Comment by rnevet** [comment]
You can try accessing the link I provided from Console...

**Comment by laxdog** [comment]
Hey @SearchAndDestroy , you won't be able to use that feature on a free account at python anywhere. You can only access sites that are on their whitelist : https://www.pythonanywhere.com/whitelist/

Though as you say, the value for USDT will be pretty much the same.

**Comment by SearchAndDestroy** [comment]
Oh ok thanks :) I never used pythonanywhere before.
