### ISSUE TITLE
Rate goes up and down slowly

### ISSUE THREAD

**Issue by kryztoval** [Mikadily/poloniexlendingbot#264]
Is it normal for rate to go up and down automatically?

![image](https://cloud.githubusercontent.com/assets/5733028/23991021/7a42ae9a-09fd-11e7-8acc-121cf8324253.png)

I am Using custom mindailyrate 0.1700% but it keeps going up and down on its own. Did I misconfigure something?

**Comment by rnevet** [comment]
See the Market Analysis configuration it provides a dynamic rate.

**Comment by kryztoval** [comment]
Oh, that makes sense. And sorry for the misleading error message, I added a bit of detail to it because I like to know what the bot is thinking it is doing. 

Is it mentioned anywhere and I missed it in the documentation?

**Comment by kryztoval** [comment]
Yes, yes it is, it wasn't clear to me why it was asking for mindailyrate if marketanalisys is on, maybe adding a warning in the log would be a good idea?

**Comment by kryztoval** [comment]
Can this be closed?
