### ISSUE TITLE
Lending earnings summary

### ISSUE THREAD

**Issue by kryztoval** [Mikadily/poloniexlendingbot#265]
Is there anyway to see how much you have made in lending?

This sounds kind of hard to implement, but I would really like that.

Just throwing ideas.

**Comment by caotic112** [comment]
you can login in poloniex, "mytrade history and analysis", than you select BTC and loan Earnings and finally click analize.

**Comment by kryztoval** [comment]
Yeah, you can also go into lending and make lendings by hand. But that is not the point, is it? @caotic112

**Comment by caotic112** [comment]
absolutly, here I'm just suggesting you an easy way to calculate how muth you have done in lending.

**Comment by kryztoval** [comment]
I know how to calculate it already, what I say was if it would be too much to ask for the bot to let me know how much I made using it.

**Comment by rnevet** [comment]
@kryztoval there is quite a lot of history in the issues of PRs, this specific issue has been raise in this PR:
https://github.com/Mikadily/poloniexlendingbot/pull/114
