### ISSUE TITLE
Year Compound Interest

### ISSUE THREAD

**Issue by kryztoval** [Mikadily/poloniexlendingbot#266]
If poloniex only allows a minimum of 2 days before you can take out the interest, and without running an analysis on how long the actual loans are... wouldn't it be more appropriate to calculate it as interest rate powered to 182 days instead of 365 days? 

This is due to the fact that you can't reinvest the interests unless they are deposited into your account and you have no way to set it to less than 2 days.

Isn't this right?

**Comment by rnevet** [comment]
It would be right if loans would actually be returned after 2days, the reality is that they can be returned after 1min... So 365 or 182 is anyway a very rough estimate

**Comment by rnevet** [comment]
Not to mention that this is all based on a very inaccurate assumption that the lending rate will remain for one year.

**Comment by kryztoval** [comment]
I agree, the value is an estimate, but can we say that the least you would bet if you set all to 2 days and the rate does not change is power of 182.

**Comment by laxdog** [comment]
The rates on the loans are daily rates. 365 is the correct value to use.

**Comment by kryztoval** [comment]
@laxdog i disagree, the capitalization is not daily. So the formula should be (t*ir+1)^(365/t)

Being t=days, ir=daily interest rate.

That would yield the minimum interest you can acrue in that amount of time if the interest rate stays the same. of course if time of interest payment is sooner or interest rate changes the sum will change. But I believe the 365 power is misleading.

**Comment by yura-pakhuchiy** [comment]
@kryztoval 

As @rnevet already said, loans can be returned in any moment. So there is no way to predict capitalization rate.
But actually there is no big difference whether we use 182.5, 365 or even 3650.
For example with effective daily rate 0.07092%
(((0.07092÷100+1)^365)−1)×100 ~= 29.533098884%
(((0.07092÷1000+1)^3650)−1)×100 ~= 29.543794744%
(((0.07092×2÷100+1)^182.5)−1)×100 ~= 29.521226293%
I do not think anybody cares about 0.01% in this case.

**Comment by yura-pakhuchiy** [comment]
For bigger daily rates difference may be bigger, but anyway rates newer stay at 30% p.a., so compound interest does not matter for them (because there is no way it will stay that high all the time). However for average rates like 4-12% p.a compound interest makes sense and pretty accurate.

**Comment by kryztoval** [comment]
True, it is only significative if it goes above 0.25% which has been the case for the past few weeks on dash and the past couple of days in bitcoin.

I also agreed that it can be returned at any time, but since you can't predict how soon they will be returned but you can predict that they won't take longer than 2 days... as long as prediction goes it seemed more accurate and sure, if 1% was the daily rate it would make a 2.78% difference. Maybe I am just a math nerd.

This seems irrelevant then.

**Comment by rnevet** [comment]
"you can predict that they won't take longer than 2 days" - I have loans up to 60 days.
Loan periods are configurable and not predictable. 

Basically, options are:
1. Change it locally for yourself. Keep this change when updating. (https://github.com/Mikadily/poloniexlendingbot/blob/master/www/lendingbot.js#L126)
2. Create a URL param configuration option for it, document it, make a pull request.

**Comment by kryztoval** [comment]
@rnevet  Yes, but that is your choice. you can pick 2 days is still the minimum time lapse you can pick that guarantees fastest returns. you can't pick any less than that.
