### ISSUE TITLE
python 3 error

### ISSUE THREAD

**Issue by sanitariu** [Mikadily/poloniexlendingbot#27]
Does not work on python3.
Need some fixes print is now print("something")
also other stuff like:

  File "lendingbot.py", line 151
    print loanOffers.get('error')
                   ^
SyntaxError: invalid syntax

**Comment by Mikadily** [comment]
I think it's much easier to install python 2, isn't it? But thanks for reporting

**Comment by sanitariu** [comment]
Hi,
yeah i did that :)

Regards,
Todor
