### ISSUE TITLE
HTTP Error 429

### ISSUE THREAD

**Issue by kryztoval** [Mikadily/poloniexlendingbot#270]
I am starting to get this errors as soon as I enabled another coin, I had 1 initially and now I have 2.
Error: HTTP Error 429: Too Many Requests Requesting returnActiveLoans

I wonder if it is something else, or if there are any changes I should make?

**Comment by laxdog** [comment]
Can you post the full stack trace? That gets called in a few places. 

Could be that your running one of the timers quite low (though that shouldn't matter) or could just be polo responding to the recent DDoS attack.

**Comment by mike4001** [comment]
I am also getting the Error: HTTP Error 429 on a regular basis with "Too Many Requests Requesting returnAvailableAccountBalances", "Too Many Requests Requesting createLoanOffer" and "Too Many Requests Requesting returnActiveLoans"

A couple of minutes later the bot gets the info and continues working, but I don´t know whats happening there since I use sleeptimeactive = 180 and sleeptimeinactive = 300

**Comment by rnevet** [comment]
Are you using multiple instances of the Not?

**Comment by mike4001** [comment]
No, I don't

Though I am running the bot on www.pythonanywhere.com - Could this be a problem (much access from the same IP from many different users?)

I will try running the bot from my raspberry pi and see if the Errors go away there.

**Comment by kryztoval** [comment]
No, I am just running one instance, and my ip is not shared.

**Comment by laxdog** [comment]
OK, I've now been getting the same error. It doesn't look to be having any adverse effects on the bot though. 

There's no stack trace in my log as we're catching those errors now, though it seems to be happening across at least two functions: returnAvailableAccountBalances and returnActiveLoans.

I'll have a closer look at it shortly. I don't think it's anything to worry about too much though.

**Comment by kryztoval** [comment]
I think this has to do with the attack. It keeps running. But shows several warnings.

Mar 21 17:29:55 python[25853]: 2017-03-21 17:29:55 Error: HTTP Error 502: Bad Gateway Requesting returnActiveLoans
Mar 21 17:29:55 python[25853]: Caught HTTP Error 502: Bad Gateway Requesting returnActiveLoans from Poloniex, ignoring.
Mar 21 19:23:39 python[25853]: 2017-03-21 19:23:39 Error: HTTP Error 502: Bad Gateway Requesting returnActiveLoans
Mar 21 19:23:39 python[25853]: Caught HTTP Error 502: Bad Gateway Requesting returnActiveLoans from Poloniex, ignoring.
Mar 21 19:33:23 python[25853]: 2017-03-21 19:33:23 Error: The read operation timed out Requesting returnOpenLoanOffers
Mar 21 19:33:23 python[25853]: Timed out, will retry in 30.0sec
Mar 21 19:35:48  python[25853]: 2017-03-21 19:35:48 Error: HTTP Error 502: Bad Gateway Requesting returnBalances
Mar 21 19:35:48 python[25853]: Caught HTTP Error 502: Bad Gateway Requesting returnBalances from Poloniex, ignoring.
Mar 21 19:36:27 python[25853]: 2017-03-21 19:36:27 Error: HTTP Error 502: Bad Gateway Requesting returnActiveLoans
Mar 21 19:36:27 python[25853]: Caught HTTP Error 502: Bad Gateway Requesting returnActiveLoans from Poloniex, ignoring.
Mar 21 19:37:35 python[25853]: 2017-03-21 19:37:35 Error: The read operation timed out Requesting returnBalances
Mar 21 19:37:35 python[25853]: Timed out, will retry in 30.0sec
Mar 21 19:38:50 python[25853]: 2017-03-21 19:38:50 Error: HTTP Error 502: Bad Gateway Requesting returnAvailableAccountBalances
Mar 21 19:38:50 python[25853]: Caught HTTP Error 502: Bad Gateway Requesting returnAvailableAccountBalances from Poloniex, ignoring.
Mar 21 19:41:02 python[25853]: Error in MarketAnalysis: The read operation timed out Requesting returnLoanOrders
Mar 21 19:41:02 python[25853]: 2017-03-21 19:41:02 Error: The read operation timed out Requesting returnLoanOrders
Mar 21 19:41:02  python[25853]: Timed out, will retry in 30.0sec
Mar 21 19:42:11 python[25853]: Error in MarketAnalysis: The read operation timed out Requesting returnLoanOrders
Mar 21 19:42:11 python[25853]: 2017-03-21 19:42:11 Error: HTTP Error 500: Internal Server Error Requesting returnOpenLoanOffers
Mar 21 19:42:11 python[25853]: Caught HTTP Error 500: Internal Server Error Requesting returnOpenLoanOffers from Poloniex, ignoring.
Mar 21 19:44:05 python[25853]: Error in MarketAnalysis: The read operation timed out Requesting returnLoanOrders
Mar 21 19:44:05 python[25853]: Error in MarketAnalysis: The read operation timed out Requesting returnLoanOrders
Mar 21 19:44:05 python[25853]: 2017-03-21 19:44:05 Error: The read operation timed out Requesting returnLoanOrders
Mar 21 19:44:05 python[25853]: Timed out, will retry in 30.0sec
Mar 21 19:46:37 python[25853]: Error in MarketAnalysis: The read operation timed out Requesting returnLoanOrders

**Comment by rnevet** [comment]
Is this still happening?

**Comment by mike4001** [comment]
It´s still happening for me.

Couple of Errors per hour

2017-03-27 05:10:12 Error: HTTP Error 429: Too Many Requests Requesting returnActiveLoans
2017-03-27 04:53:30 Error: HTTP Error 429: Too Many Requests Requesting returnAvailableAccountBalances
2017-03-27 04:22:46 Error: HTTP Error 429: Too Many Requests Requesting returnActiveLoans
...
...

**Comment by rnevet** [comment]
Did you try moving from pythonanywhere?

**Comment by mike4001** [comment]
No, sorry. My Pi3 is not available at the moment.

**Comment by rnevet** [comment]
I don't have an explanation other then it being a shared environment. In any case the bot should continue.

**Comment by mike4001** [comment]
Yes, the bot is working without any problems.

It would be nice if we could supress the Error messages though as they are "cluttering" the trading history.

**Comment by laxdog** [comment]
Agreed, initially I'd thought it would be useful for people to see these, but I think it's better to hide them and add them in a debug log or something.

**Comment by rnevet** [comment]
I have to say that this is an issue. if it persists for every call for example, the bot is actually not working. I wouldn't hide the issue.

**Comment by mike4001** [comment]
Just wanted to let you know that the issue is gone for me at the moment (without me changing anything).

Maybe Poloniex changed some server-side stuff.
