### ISSUE TITLE
Bot places loans below minloansize (keepstuckorders = False)

### ISSUE THREAD

**Issue by mike4001** [Mikadily/poloniexlendingbot#271]
Hi

I am having the problem that the bot is placing loans below minloansize (= 0.02 in my case)

I thought it where stuck orders, so I configured "keepstuckorders = False" but it didn´t change anything.

Enclosed you get my default.cfg and a pictures from poloniex of my low loans

[default.cfg.txt](https://github.com/Mikadily/poloniexlendingbot/files/853164/default.cfg.txt)
![low loans](https://cloud.githubusercontent.com/assets/26521177/24080668/97621070-0ca4-11e7-9c7f-86b6d3066864.jpg)

**Comment by rnevet** [comment]
The bot loan size defines the size of the offers made, which you can see in the logs. However also partial loans can be taken - that's just how Poloniex defined it.
