### ISSUE TITLE
HTTP Error 422

### ISSUE THREAD

**Issue by flufy3d** [Mikadily/poloniexlendingbot#273]
Welcome to Poloniex Lending Bot
2017-03-24 23:32:17 Error: HTTP Error 422:  Requesting returnOpenLoanOffers
Caught HTTP Error 422:  Requesting returnOpenLoanOffers from Poloniex, ignoring.

There seems to be an issue with recent poloniex server changes for DDOS protection

**Comment by laxdog** [comment]
You can ignore this, the bot will continue to operate after this message. 

Let me know if that's not the case.

**Comment by rrobledo74** [comment]
Maybe it's because Polo has been slammed with attacks lately, but the bot has been getting the same error since Friday. The only thing I've edited in the cfg file (other than adding my keys), was changing "xdays =2". Hope you can help. Thanks!

**Comment by cassidykeyser** [comment]
I'm getting the same error, I am also starting the webserver and it's not writing the botlog.json to the www folder (default settings).

Any ideas?
