### ISSUE TITLE
error loop http 422

### ISSUE THREAD

**Issue by keepthefaya** [Mikadily/poloniexlendingbot#277]
hi, i got 422 http error, anyone have same trouble  ? Problem from poloniex or my conf ?
Thanks  for your back

python lendingbot.py
Welcome to Poloniex Lending Bot
2017-03-29 05:57:28 Error: HTTP Error 422:  Requesting returnActiveLoans
Caught HTTP Error 422:  Requesting returnActiveLoans from Poloniex, ignoring.
2017-03-29 05:58:29 Error: HTTP Error 422:  Requesting returnActiveLoans
Caught HTTP Error 422:  Requesting returnActiveLoans from Poloniex, ignoring.
2017-03-29 05:59:29 Error: HTTP Error 422:  Requesting returnActiveLoans
Caught HTTP Error 422:  Requesting returnActiveLoans from Poloniex, ignoring.

**Comment by kryogenic** [comment]
Try deleting your API key and creating a new one.

**Comment by keepthefaya** [comment]
i have try to generate new api key, its seems to be work now my loans are filled, but nothing to return into my sheel and frontend 127.0.0.1:800 (into conf file) seems not to be up

timeout on frontend

Any idea?

**Comment by kryogenic** [comment]
You have to enable the frontend in default.cfg. Try the [gitter](https://gitter.im/Mikadily/poloniexlendingbot?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) or the [docs](http://poloniexlendingbot.readthedocs.io/en/latest/index.html) for additional questions.

**Comment by laxdog** [comment]
You can normally ignore any messages where the bot tells you it's ignoring it. They're nothing we can fix and are issues with Poloniex.

**Comment by keepthefaya** [comment]
ok thanks @kryogenic @laxdog
