### ISSUE TITLE
Notification config value being ignored

### ISSUE THREAD

**Issue by kryogenic** [Mikadily/poloniexlendingbot#278]
Hi, it seems that (at least using telegram notifications) the value for `notify_xday_threshold` is always considered to be True.

Also, to avoid spamming I think it would be much better if a notification was sent only if a loan offer was filled. Currently `notify_xday_threshold` sends a notification every time a loan offer is placed, and since the bot cancels and replaces all orders every minute or so, this can result in a lot of notifications being sent.

Granted, I am using a very large value for `gaptop` (20000%), so my bot almost always has an xday offer open.

**Comment by laxdog** [comment]
Yip, you're completely right about the always True, in fact I think it's an bug for the others too. I'll have a look at it. 

I also agree about only notifying when the order is filled. I didn't add it as I knew it would have been a lot more complicated and I wasn't sure if anyone was going to use the notification features. I can have a look at adding it though.

**Comment by kryogenic** [comment]
I would almost say there should instead be a separate config value that notifies each time an order is filled. That would be a feature request though so I'll leave it up to you whether you wanna embark on it. Thanks!

**Comment by laxdog** [comment]
Yea, I reckon if I was going to do it I'd leave both. It's a feature request either way ;)

I'm just not sure exactly how to do it. I'll have to keep track of the active loans and check the time of the newest one against the last run time or something. There's potential to add it into some of the market analysis stuff, or at least leverage some of it.

**Comment by kryogenic** [comment]
Ahh yeah I would want to connect to their websocket or something. I'm not sure but returnLendingHistory may also work. However it looks like the bot currently doesn't use either of those.

**Comment by laxdog** [comment]
I think you can only get the public information from the web socket, the only way to get your loan stuff is through the REST API. 

returnLendingHistory will only show the completed loans, though that's something I'd like to add too.

**Comment by kryogenic** [comment]
Ok I went ahead and partially implemented this, it's quite messy and just prints to console instead of actually sending the notifications but hopefully this gives you something to work off of!

All I did was add a little bit to the top of get_total_lends() in modules/Data.py:

`loans_provided = {}

def get_total_lended():
    global loans_provided
    crypto_lended = api.return_active_loans()
    if loans_provided == {}:
        loans_provided = crypto_lended['provided']
    else:
        new_loan_ids = set(map(lambda l: l['id'], crypto_lended['provided'])) - set(map(lambda l: l['id'], loans_provided))
        if new_loan_ids:
            print('new loans found: ', new_loan_ids)`

**Comment by kryogenic** [comment]
Closed #281
