### ISSUE TITLE
BTC per week/month is not using compound interest

### ISSUE THREAD

**Issue by mike4001** [Mikadily/poloniexlendingbot#279]
Hi

Title says it all

A quick calculation showed that the BTC per week and per month in the web interface are just using a multiplication *7 and *30 and are not correctly using the compound interest to calculate these figures.

In my case monthly BTC would be around 3% higher than what is shown in the web interface.

**Comment by laxdog** [comment]
I don't think you're right. The second of the two 'Year' values shows the compound interest. The calculation is 

```
var yearlyRateReinv = (Math.pow(effectiveRate / 100 + 1, 365) - 1) * 100; // with daily reinvestment
```

Can you show exactly what you mean please @mike4001 ?

**Comment by mike4001** [comment]
Yes, this part is correct

But I mean 

![unbenannt-1](https://cloud.githubusercontent.com/assets/26521177/24452400/62aa0bf8-1483-11e7-9e98-6777e657881d.jpg)

**Comment by laxdog** [comment]
Ah, ok. Sorry, I misread the issue. Yes, you're completely right. The function that does it is here:


```
  233 function Timespan(name, multiplier) {
  234     this.name = name;
  235     this.multiplier = multiplier;
  236     this.calcEarnings = function(sum, rate) {
  237         return sum * rate * this.multiplier;
  238     };
```

It should be 
```
return sum * Math.pow(1 + rate, multiplier) - sum;
```
 I think

**Comment by laxdog** [comment]
Fixed here: https://github.com/Mikadily/poloniexlendingbot/pull/280

**Comment by laxdog** [comment]
Can you test and close @mike4001 ?

The latest master has the fix.

**Comment by mike4001** [comment]
I replaced the files (and also see the codechange) but the webinterface still shows the figures without compound interest.

Can someone else check if it is fixed for them ?

**Comment by rnevet** [comment]
As this is a JS change, you might need to force refresh Ctrl+f5.

**Comment by mike4001** [comment]
That did the trick, thank you!
