### ISSUE TITLE
Failed to start WebServer: [Errno 8] nodename nor servname provided, or not known

### ISSUE THREAD

**Issue by songproducer** [Mikadily/poloniexlendingbot#282]
Hi,

I just uncommented:

jsonfile = www/botlog.json
jsonlogsize = 200
startWebServer = true

**Comment by rnevet** [comment]
could be something related to you local setup.
Try un commenting this line as well:
customWebServerAddress = 0.0.0.0:8000

**Comment by songproducer** [comment]
Tried uncommenting that line too but still same error msg.

**Comment by songproducer** [comment]
Changing it to 127.0.0.1:8000 did the trick!

**Comment by rnevet** [comment]
Great
