### ISSUE TITLE
Not a bot issue but a Poloniex one

### ISSUE THREAD

**Issue by fireburndread** [Mikadily/poloniexlendingbot#285]
This statement essentially means if your BTC is loaned out during the hard-fork, all the BTC Unlimited would go to the person borrowing your BTC

https://poloniex.com/press-releases/2017.03.17-Hard-Fork/

Do factor this into your rates.
Cheers all!

**Comment by rnevet** [comment]
Correct, this was also what happened in the ETH/C fork.

**Comment by fireburndread** [comment]
Thanks. Just to confirm, those who keep their coins in their own account would have 1 of each coin?

**Comment by rnevet** [comment]
As far as I understand and as it happened with ETH.

I received ETC for my ETH on Poloniex but not for what was lent.

**Comment by rnevet** [comment]
As BU doesn't seem to be imminent I'm closing this issue.
