### ISSUE TITLE
if new notification parameters are missing can't start

### ISSUE THREAD

**Issue by utdrmac** [Mikadily/poloniexlendingbot#293]
Please add some built-in defaults (all off/false) to the new notifications additions. I discovered that if they are not present in the default.cfg, bot refuses to start:

```
root@gasgiant:/usr/src/poloniexlendingbot# /usr/bin/python /usr/src/poloniexlendingbot/lendingbot.py
Traceback (most recent call last):
  File "/usr/src/poloniexlendingbot/lendingbot.py", line 58, in <module>
    Lending.init(Config, api, log, Data, MaxToLend, dry_run, analysis, notify_conf)
  File "/usr/src/poloniexlendingbot/modules/Lending.py", line 80, in init
    if notify_conf['notify_summary_minutes']:
KeyError: 'notify_summary_minutes'
```

I'm not using these features so the absence of their config parameters should not be causing failures.

**Comment by rnevet** [comment]
@kryogenic related to recent changes

**Comment by kryogenic** [comment]
Whoops, sorry about this. Turns out the notification config values only have defaults if the config file has a `[notifications]` section. #295 should remedy the situation.
