### ISSUE TITLE
Hide coins enhancement

### ISSUE THREAD

**Issue by AlexMinty** [Mikadily/poloniexlendingbot#299]
for example: 

If the minimum lend rate is set at .03 and there is one loan that someone has returned at .029, and even though the majority of loans available are above the min lend rate set, the bot will not lend out anything because it sees a single offer below .03

Would it possible to set a threshold of number of loans for the bot to ignore below the min lend rate? For example : ignore X number of offers below min lend rate and let the bot offer loans above or at the minimum lend rate set?

**Comment by Evanito** [comment]
You can do
```
#Hide coins - Instead of keeping your coins lent out at minlendrate when it is not met, the bot will hold them and wait for the rate to surpass it.
hideCoins = False
```
to lend at .3 anyway.

Otherwise, gaptop and gapbottom settings are meant for skipping dust in the lendbook.

**Comment by AlexMinty** [comment]
Brainfart on my part, cheers Evanito
