### ISSUE TITLE
feature request minRate no lending

### ISSUE THREAD

**Issue by sanitariu** [Mikadily/poloniexlendingbot#30]
"In case the going rates are lower than minRate I agree that it shouldn't loan at all, right now the behavior is to create a loan at maxRate."

Will you implement that feature. Not lending if is lower than minRate...

**Comment by Mikadily** [comment]
We discuss it here:
https://github.com/Mikadily/poloniexlendingbot/issues/26

**Comment by rnevet** [comment]
A more detailed feature request here:
https://github.com/Mikadily/poloniexlendingbot/issues/46
