### ISSUE TITLE
Custom mindailyrate being overridden by something else

### ISSUE THREAD

**Issue by songproducer** [Mikadily/poloniexlendingbot#300]
Problem is btc isn't being lent.

```
2017-04-19 15:49:53 Not lending BTC due to rate below 0.1000%
2017-04-19 15:49:52 Using custom mindailyrate 0.0400% for BTC
```

Not sure where it's getting 0.1% from. I've disabled the Local Market Analysis and set BTC like so:

[BTC]
minloansize = 0.2 
mindailyrate = 0.04
maxactiveamount = 1
maxtolend = 30
maxpercenttolend = 0
maxtolendrate = 1

**Comment by laxdog** [comment]
1) Are you sure Market Analysis is off?
2) Do you have the coinconfig line commented out?

**Comment by songproducer** [comment]
Closing for now since not reproducable.
