### ISSUE TITLE
Maximum lendig rate

### ISSUE THREAD

**Issue by shimoda** [Mikadily/poloniexlendingbot#308]
#Maximum lending rate. 2% is good choice because it's default at margin trader interface.
#5% is the maximum rate accepted by the exchange (0.003-5)
maxdailyrate = 2

Is there any downside to always having maxdailyrate = 5? Why choose a lower than maximum possible rate?
I know I could read the code and figure this out, but call me lazy :)

**Comment by rnevet** [comment]
No downside from bot perspective.

**Comment by shimoda** [comment]
Ok. Why is 2% a good choice? (as written in the comment) Why not always 5%?

**Comment by rnevet** [comment]
You can say that max limits your spread.

**Comment by shimoda** [comment]
Ok. Thanks for the info. You have a very good product here, Like it.

**Comment by rnevet** [comment]
I don't think 2 or 5 matters.
