### ISSUE TITLE
Error "Provided"

### ISSUE THREAD

**Issue by twoshoes22** [Mikadily/poloniexlendingbot#31]
I keep getting the following error with auto-renew on:

> 
> 2016-03-20 19:05:53 Welcome to Poloniex Lending Bot
> 2016-03-20 19:05:53 Clearing AutoRenew...(Please Wait)
> Traceback (most recent call last):
>   File "lendingbot.py", line 246, in <module>
>     setAutoRenew(0);
>   File "lendingbot.py", line 223, in setAutoRenew
>     loansCount = len(cryptoLended["provided"])
> KeyError: 'provided'

If I set autorenew to 0, I instead get this error in the log:

> 
> 2016-03-20 19:08:24 Welcome to Poloniex Lending Bot
> 2016-03-20 19:08:24 ERROR: 'provided'
> 2016-03-20 19:08:54 ERROR: 'provided'
> 2016-03-20 19:09:24 ERROR: 'provided'
> 2016-03-20 19:09:54 ERROR: 'provided'

**Comment by Mikadily** [comment]
Did you type in your API key and secret right in the config?

**Comment by twoshoes22** [comment]
I copy pasted them from poloniex, and tried with double quotations marks, single quotation marks and no quotation marks, just to make sure.

I put in the code:
print(config.get("API","apikey"))
print(config.get("API","secret"))

It does seem to be able to get the key and secret key from the Config file.

If the api keys are invalid (and I'm copy/pasting them from poloniex), would I be getting an error regarding that?

**Comment by Mikadily** [comment]
ERROR: 'provided' normally means connectivity issues (I know it's not informative). Try to dig github issue history, I remember people had problems with IP whitelisting and running several bots with same keys. Maybe you'll find something there.

**Comment by twoshoes22** [comment]
I'll see what I can discover, but I think the Ip whitelisting feature is off on my poloniex account, and I'm not running other bots. 

How should the apikey and secretkey be formatted in the config file? No quotation marks?

**Comment by twoshoes22** [comment]
It turns out it worked after I created a new API key. Very strange.

Still would be nice to know if quotation marks belong in the config file. :)

**Comment by Mikadily** [comment]
No quotation. Just plain keys.

**Comment by twoshoes22** [comment]
Thanks for the help.

I have a suggestion, have you thought about splitting the current balance into 10-20 orders and posting them up onto the orderbook. Now it seems like it just keeps filling the lowest price.

**Comment by Mikadily** [comment]
It should be splitting - the config option spreadlend.

If you'd show me your config (without api keys) and tell me which coin you are using, I could tell you why the bot decided not to split.

**Comment by twoshoes22** [comment]
Been testing it on btc.
```
#sleep between iterations, time in seconds
sleeptime = 30
#minimum daily lend rate in percent
mindailyrate = 0.09
#max rate. 2% is good choice because it's default at margin trader interface. 5% is max to be accepted by the exchange
maxdailyrate = 2
#The number of offers to split the available balance uniformly across the [gaptop, gapbottom] range.
spreadlend = 20
#The depth of lendbook (in percent of lendable balance) to move through before placing the first (gapbottom) and last (gaptop) offer.
#if gapbottom is set to 0, the first offer will be at the lowest possible rate. However some low value is recommended (say 10%) to skip dust offers
gapbottom = 18
gaptop = 80
#Daily lend rate threshold after which we offer lends for 60 days as opposed to 2. If set to 0 all offers will be placed for a 2 day period
sixtydaythreshold = 0
# AutoRenew - if set to 1 the bot will toggle the AutoRenew flag for the loans when you stop it (Ctrl+C) and clear the AutoRenew flag when started
autorenew = 1
#custom config per coin, useful when closing positions etc.
#syntax: [COIN:mindailyrate:maxactiveamount, ... COIN:mindailyrate:maxactiveamount]
#if maxactive amount is 0 - stop lending this coin. in the future you'll be able to limit amount to be lent.
#coinconfig = ["BTC:0.18:1","CLAM:0.6:1"]

```

**Comment by Mikadily** [comment]
Your gaptop is too low. If you want many many splits (not sure why would you), try setting it to 100*200/x ; where x is number of coins you're lending. So if you have 1 btc, you gaptop should be 20000. 100 btc - gaptop = 200.

**Comment by twoshoes22** [comment]
Thank you for all the suggestions.
