### ISSUE TITLE
average rate overstated due to 15% taxation

### ISSUE THREAD

**Issue by clf99** [Mikadily/poloniexlendingbot#320]
polo charges a 15% fee they eat out of your winnings from loans.
so the average interest rate displayed by the tool is arguably overstated and should be displayed thusly:

rate: .2234% netRate: .85*.2234=.1899%

or whatever....

thanx for an awesome python winner tool that is printing me money rite now

**Comment by rnevet** [comment]
This is due to line size limitations in console. Use the HTML interface for full information.
