### ISSUE TITLE
Bot stops running every few days on pythonanywhere

### ISSUE THREAD

**Issue by mike4001** [Mikadily/poloniexlendingbot#322]
Hi,

I have the problem that the bot is basically running just fine but every few days (sometimes 12 hours, sometimes 3-4 days) the bot just stops.

When I look at the pythonanyhwere console either
1) Console is still running but there is no process running anymore.
2) Console + process are both not running anymore.

Is there any way I can look up what is causing this?

**Comment by laxdog** [comment]
Are you running the webgui? Has it logged anything?

In the case where the console is still running, are there any logs on screen?

**Comment by mike4001** [comment]
Yes I am running the webgui. At some point it just stops refreshing. And also a quick look into Poloniex confirmes that no more loans are created.

I will check if the console shows anything the next time it happens. (Can't be long) :-)

**Comment by mike4001** [comment]
OK, just happened again.

The problem is that the console was still shown under "Your consoles:", but when clicking on it it just started the console and the bot from scratch.

So I cannot see any error logs.

**Comment by rnevet** [comment]
Can you redirect the bot output into a log file?

**Comment by mike4001** [comment]
Sorry, you would have to tell me how ...

**Comment by rnevet** [comment]
try:
python lendingbot.py | tee log.txt

Not sure about how pythonanywhere works.

**Comment by mike4001** [comment]
OK, I restarted the console and now see the log.txt in the home directory with line 1 "Welcome to Poloniex Bot"

Now we wait :-)

**Comment by rnevet** [comment]
Sorry, I updated the command, it should include also the error output (before it didn't).

**Comment by mike4001** [comment]
OK I updated the command, the bot stopped again over night but there was no Error in the log.txt.

It just said the same loan information I also see via the webinterface which just stops at one moment.

I am going to remove all files from pythonanywhere and upload the whole bot again and also start a new config file ... maybe I did something that was wrong before.

**Comment by mike4001** [comment]
OK, I moved the bot to my Raspberry Pi and the problem is gone.

Running for 3-4 days now without of any problems, so I guess this was a pythonanywhere problem.

**Comment by rnevet** [comment]
Thanks for the update.

**Comment by otaviobps** [comment]
I'm having the same problem with pythonanywhere. The bot suddenly stops and I have to kill the console and start it again. Maybe is a problem with the site. I'm using pythonanywhere because it was easy to configure the webapp.

**Comment by Proo-cpu-vps** [comment]
Pythonanywhere consoles can stop in 34-48 hours and they will restart again.If you want to without stop you can run your bot via this command:
nohup python3 script.py &
