### ISSUE TITLE
Many Error: HTTP Error 502: Bad Gateway

### ISSUE THREAD

**Issue by sospcie** [Mikadily/poloniexlendingbot#327]
Hello,

Did something changed on Poloniex side which generate lots of errors like the following?

- Error: HTTP Error 502: Bad Gateway Requesting returnActiveLoans
- Error: HTTP Error 502: Bad Gateway Requesting returnOpenLoanOffers

**Comment by rnevet** [comment]
Yes, they are under stress and not handling it well.

**Comment by sospcie** [comment]
Thank you. At least that confirms that the script is ok:) And I hope Poloniex will do things better soon.
