### ISSUE TITLE
Change default action when maxactive amount =0

### ISSUE THREAD

**Issue by raitpngman** [Mikadily/poloniexlendingbot#33]
When individual coins are specified and maxactive amount=0 and there is already an open loan for that coin, the bot removes the loan. It would be best to ignore that coin in all respects if maxactive=0. In other words, please don't remove open loans for coins where maxactive=0

**Comment by Mikadily** [comment]
The purpose of maxactive, is to stop lending and be able to withdraw a specific coin. For something what you ask we might need another feature - something like 'ignore coin'.

**Comment by raitpngman** [comment]
Fair enough. I imagine this should be low priority if at all. Most people wouldn't be trying to do manual and automatic lending at the same time. I ran into this because I was trying to test parameters but I didn't want it to lend the other alt coins in case I got it "wrong".
