### ISSUE TITLE
Having trouble setting this up. Will pay someone for help

### ISSUE THREAD

**Issue by Zeek1010** [Mikadily/poloniexlendingbot#333]
Id like to pay someone to take 20 mins of their time to help me set this code up. Please email me at zachay.goldberg@rocketmail.com Willing to pay 40$. Thank you

**Comment by utdrmac** [comment]
@Zeek1010 
```
554 delivery error: dd This user doesn't have a rocketmail.com account (zachay.goldberg@rocketmail.com) [0] - mta1545.mail.bf1.yahoo.com
```

**Comment by Zeek1010** [comment]
sorry typo,  zachary.goldberg@rocketmail.com

**Comment by Zeek1010** [comment]
figured it out, thanks guys
