### ISSUE TITLE
One click deploy

### ISSUE THREAD

**Issue by laxdog** [Mikadily/poloniexlendingbot#335]
Might finally be time to look into sorting this out on heroku or somewhere. 

Seems like a lot of users are having trouble getting it running.

**Comment by rnevet** [comment]
Don't think that's possible, we can setup API keys through console on first run.

**Comment by laxdog** [comment]
You can have free text fields in heroku that are shown before the deployment that allow you to change the environment I thought?

I've used them before, but maybe they're not available for python deploys.

**Comment by laxdog** [comment]
Read https://github.com/Mikadily/poloniexlendingbot/issues/109 again. Forget this :)

Though I do like the idea of setting up the keys on first run. We could expand that to a few other things maybe too. Though those are the most important.
