### ISSUE TITLE
Summary output truncated.

### ISSUE THREAD

**Issue by raitpngman** [Mikadily/poloniexlendingbot#34]
Sorry, I don't know where else to ask questions.

I have multiple altcoins that the lending bot is controlling. I really like the output where it summarizes the coins lended. However, it truncates the output and looks like this

Lended: [0.726 BTC @ 0.1067%] [34.605 DASH @ 0.1724%] [45007.238 DOGE @ 0.0099%] [1.000 ETH @ 0....

I would love to see all the coins lent out. This gives me a great summary to figure out my progress without having to manually add all the coins or stop lending just so I can get a count of current coins.
Is there an easy way to do that now?

**Comment by Mikadily** [comment]
a very quick fix, go and edit your Logger.py:
https://github.com/Mikadily/poloniexlendingbot/blob/master/Logger.py#L58
Change 96 to more. or use this patch:
https://github.com/Mikadily/poloniexlendingbot/pull/32/commits/0dffe4840983c166d2815d24610d3aad50209c86

A better fix... I am out of ideas how to represent it

**Comment by rnevet** [comment]
@raitpngman I created a new Logger that outputs the log into a JSON file - keeping the full status and a limited log history. Also an html page that can be used to view the JSON nicely. 
You can try it under my fork or wait till it's tested and merged.

https://github.com/rnevet/poloniexlendingbot

feedback would be also appreciated.

**Comment by Evanito** [comment]
Fixed by #32

**Comment by rnevet** [comment]
https://github.com/Mikadily/poloniexlendingbot/pull/32 merged, as well as the html option is available.
