### ISSUE TITLE
What is gapbottom / gaptop

### ISSUE THREAD

**Issue by chfast** [Mikadily/poloniexlendingbot#37]
I don't understand what _the depth of lendbook (in percent of lendable balance)_ means. I have gapbottom set to 20, gaptop to 200. And the bot is placing strange offers like:

```
2016-04-04 10:00:39 Placing 0.00180554 ETH at 0.0275% for 2 days... Loan order placed.
2016-04-04 10:00:39 Placing 0.00180554 ETH at 0.0276% for 2 days... Loan order placed.
2016-04-04 10:00:39 Placing 0.00541664 ETH at 0.0277% for 2 days... Loan order placed.
```

I think it would be better to spread the offers more.

**Comment by Mikadily** [comment]
Gaptop and gapbottom are measures, of how do you want to spread your offers. If you have in your account 200 eth and your gapbottom is 20 (%). It means, skip first 40 (20% of your 200 lending balance) ETH in loan offers, then put first order. Pur the last order at 400 ETH (200% of your lending balance).

So if you want to spread more, try increasing your gaptop, to 500, 1000, 5000, 20000. Until you're happy.

**Comment by chfast** [comment]
So the prices for new offers are calculated based on my active offers? Not based on others' offers?

**Comment by Mikadily** [comment]
When I say "skip first 40 eth in loan offers" I mean others' offers on the book. In other words that's "depth of lendbook" from readme.

**Comment by Evanito** [comment]
Closed because answered by https://poloniexlendingbot.readthedocs.io/en/latest/configuration.html#spreading-your-lends
