### ISSUE TITLE
Feature Request downtime clock

### ISSUE THREAD

**Issue by AlexMinty** [Mikadily/poloniexlendingbot#44]
Adding a downtime clock to show how long your coins have not been lent out. DD:HH:MM:SS

Other exchanges may have better rates when Poloniex lending rates are below a certain percentage. By comparing the downtime we can calculate which exchange to keep our coins on.

**Comment by laxdog** [comment]
@AlexMinty How exactly would this work though? Not everyone lends out all their coins, if you're using maxtolend etc then there'll always be coins not lent out. 

The only way I can see of doing it would be via a graph, coins not lent on Y and time on X. Which is of course possible, but a lot of work.

**Comment by AlexMinty** [comment]
I didn't realise this was still open, probably an unnecessary enhancement.
