### ISSUE TITLE
Strange character in default config property jsonfile

### ISSUE THREAD

**Issue by Fornax96** [Mikadily/poloniexlendingbot#52]
https://github.com/Mikadily/poloniexlendingbot/blob/master/lendingbot.py#L43

When I tried to run file got saved as `ww??otlog.json`. I think you may have meant to save it to `www/botlog.json`

**Comment by rnevet** [comment]
I corrected it as part of this pull request:
https://github.com/Mikadily/poloniexlendingbot/pull/51

**Comment by Mikadily** [comment]
Merged
