### ISSUE TITLE
Show estimated earning rates on html page

### ISSUE THREAD

**Issue by Fornax96** [Mikadily/poloniexlendingbot#53]
I tried submitting a pull request for this but couldn't get the github commandline client working. Anyway, you can view my implementation here: http://fornax96.me/lendingbot.html. Feel free to use. It currently only shows BTC rates, but I guess you could add a loop to support others too.

I also modified the lendingbot.py script to show one more decimal so it's more accurate.

**Comment by wza** [comment]
Very interested in this.

**Comment by WesleyThurner** [comment]
I second this, would you mind sharing the code?

**Comment by Fornax96** [comment]
It's in the source of the page I added to the OP: view-source:http://fornax96.me/lendingbot.html

Basically what I did was write this function:
`function updateRates(data){
	console.log(/(\d+\.\d+) BTC/i.exec(data));
			
	var btc = /(\d+\.\d+) BTC/i.exec(data)[1];
	var percent = /BTC @ (\d+.\d+)\%/i.exec(data)[1];
	var rate = +percent / 100;
			
	var btchourly = (+btc * +rate) / 24;
	var btcdaily = (+btc * +rate);
	var btcweekly = (+btc * +rate) * 7;
	var btcmonthly = (+btc * +rate) * 30;
			
	var text = (Math.round(btcmonthly * 100000000) / 100000000) + " BTC per Month<br/>"
			+ (Math.round(btcweekly * 100000000) / 100000000) + " BTC per Week<br/>"
			+ (Math.round(btcdaily * 100000000) / 100000000) + " BTC per Day<br/>"
			+ Math.round(btchourly * 100000000) + " Satoshi per Hour<br/>";
	
	$("#rate").html(text);
}`

which gets called in `updateJson` after updating the `last_update` text like this: 
`updateRates(data.last_status);`

And I added a table row to show the information:
`<tr><th class="col-xs-2" style="vertical-align: text-top;">BTC Rate</th><th class="col-xs-10" id="rate">N/A</th></tr>`

**Comment by Fornax96** [comment]
Github's markdown code highlighting is not too well, I'll just try committing again

**Comment by m33Lucky** [comment]
Can u add the other coins pls for us non coders

**Comment by Fornax96** [comment]
Sure, I'll work on it a bit more and add it to this repo. It may not be done before Saturday.

**Comment by m33Lucky** [comment]
So far I see btc , Xmr , maid , Eth , and doge user mostly , have not heard any other coins yet

**Comment by AlexMinty** [comment]
This is excellent, thank you.

**Comment by m33Lucky** [comment]
how to use where are the files

**Comment by AlexMinty** [comment]
m33Lucky: 
open http://fornax96.me/lendingbot.html in your browser
save locally
rename to lendingbot.html

in www folder remove original lendingbot.html
copy/move new downloaded lendingbot.html into www folder
restart lendingbot.py

**Comment by Fornax96** [comment]
Easy as pie, you don't even need to restart your bot

**Comment by rnevet** [comment]
You also don't need to name it the same...

**Comment by m33Lucky** [comment]
not working class not specified and cant get json

**Comment by Evanito** [comment]
For anyone having an issue extracting the source: http://notepad.pw/iv6vy1gl

**Comment by Kili4ka** [comment]
Hi,

I've used Fornax96's html file and it works good.
I have a little different implantation of this feature and my calculations are about 15% lower.
I suppose that those calculations are gross, before reducing the exchange fees.

I would suggest to change it to the net values, as those are the numbers we are interested in.

**Comment by Evanito** [comment]
@Kili4ka Yep, lending fees are actually 15%

**Comment by Fornax96** [comment]
Added the 15% fee deduction. I'm now patching my own fork. It involves a lot of spacebar mashing.

**Comment by Kili4ka** [comment]
Thanks. works as expected.

**Comment by Kurairaito** [comment]
check at https://github.com/Mikadily/poloniexlendingbot/pull/58 for update and display all currencies

**Comment by Evanito** [comment]
Closed by #58

**Comment by rnevet** [comment]
Added ALT/BTC conversion in latest update: Improved logging with raw values https://github.com/Mikadily/poloniexlendingbot/pull/66
