### ISSUE TITLE
[Suggestion] Show BTC/hr on altcoins

### ISSUE THREAD

**Issue by Evanito** [Mikadily/poloniexlendingbot#63]
Basically, now that we have `<altcoin> per day` shown in the html file, we should go to Poloniex, get current exchange rate for the altcoin, and show how much BTC per hour/day we are getting.

We may be able to do this by:
- Getting ticker rates from poloniex.py, passing them to botlog.json, and then reading them in the .html
- Find a way (using WAMP APIs) to read ticker data straight from the poloniex API server (not probable)
- AngularJS in the html file?

**Comment by rnevet** [comment]
With the raw values logging change https://github.com/Mikadily/poloniexlendingbot/pull/66, it should be easy to call the returnTicker api when updating the status and store the needed conversion rates in the json log. I would make it conditional on enabled json logging.

**Comment by rnevet** [comment]
The poloniex ticker returns for example:
"BTC_LTC":{"last":"0.0251","lowestAsk":"0.02589999","highestBid":"0.0251","percentChange":"0.02390438",
"baseVolume":"6.16485315","quoteVolume":"245.82513926"}

What would you use for conversion rate? last?

**Comment by Evanito** [comment]
Since we are doing altcoin to btc, we should do the sell rate of the coin, so highestBid. If we want to be optimistic, we could use lowestAsk.

**Comment by rnevet** [comment]
I'll try and implement based on the https://github.com/Mikadily/poloniexlendingbot/pull/66 branch, we can merge it after.

**Comment by rnevet** [comment]
Implemented in https://github.com/Mikadily/poloniexlendingbot/pull/66

**Comment by Evanito** [comment]
Kudos! Have been busy recently, finishing up the school year @rnevet
