### ISSUE TITLE
Default config

### ISSUE THREAD

**Issue by Webonaute** [Mikadily/poloniexlendingbot#7]
Hi.

I have lot of problem with the script. first the float/decimal comparaison.
second, it always try to lend at 1.99% when the current market is 0.18%

my config is : 

#sleep between iterations, time in seconds
sleeptime = 300
#minimum daily lend rate in percent
mindailyrate = 0.4
#max rate. 2% is good choice because it's default at margin trader interface. 5% is max to be accepted by the exchange
maxdailyrate = 2
#The number of offers to split the available balance uniformly across the [gaptop, gapbottom] range.
spreadlend = 3
#The depth of lendbook (in percent of lendable balance) to move through before placing the first (gapbottom) and last (gaptop) offer.
#if gapbottom is set to 0, the first offer will be at the lowest possible rate. However some low value is recommended (say 10%) to skip dust offers
gapbottom = 1
gaptop = 100
#Daily lend rate threshold after which we offer lends for 60 days as opposed to 2. If set to 0 all offers will be placed for a 2 day period
sixtydaythreshold = 0

**Comment by Mikadily** [comment]
Your mindailyrate (0.4) is way out of range. It's not   even on the order books. When this happens scripts leans to a max rate (2%). If order book get's somewhere close 0.4, the script will readjust. Try lower rate 0.05-0.1, or anything that's on order book.

As for decimal comparison, any error message?

**Comment by Webonaute** [comment]
Thank. look to work now.
