### ISSUE TITLE
Program crash unable to start

### ISSUE THREAD

**Issue by m33Lucky** [Mikadily/poloniexlendingbot#74]
When value of mindailyrate is change to 0.001 as doge rate is too LOW now please fix my half a million doge sitting idle

**Comment by rnevet** [comment]
Try using coinconfig specifically for DOGE, coinconfig doesn't have the strict limitations.

```
coinconfig = ["DOGE:0.001:2"]
```

**Comment by m33Lucky** [comment]
Tried still giving at 0.01 when config was set to 0.0001

**Comment by rnevet** [comment]
coinconfig - coin names must be in CAPS.
