### ISSUE TITLE
[Suggestion] Don't cancel loans that can't be replaced

### ISSUE THREAD

**Issue by Evanito** [Mikadily/poloniexlendingbot#75]
Sometimes, loans get partially filled and leave something like .0009 leftover, then the bot comes and cancels it.

Since the balance isn't over .001, the bot can't replace the loan, wasting time and money.

Solution: Don't cancel loans under .001

**Comment by rnevet** [comment]
The side effect can be that if the going rate went down those loans will not be taken either.

**Comment by Evanito** [comment]
If the going rate goes down it won't matter because we won't be able to lend anyway

We should, instead of doing loanAmt > .001, do loanAmt + coinAmtInLendingWallet > .001 because if we cancel that loan we will still be over .001 and able to place one. Otherwise, leave it because its slightly better than not being able to loan at all.

**Comment by rnevet** [comment]
loanAmt + coinAmtInLendingWallet > .001  that makes sense, don't cancel if you can't create a loan with what's left after.

**Comment by rnevet** [comment]
Don't have time right now to properly test this but this should be something like from line 282:
```
	lendingBalances = bot.returnAvailableAccountBalances("lending")['lending']

	onOrderBalances = {}
	for cur in loanOffers:
		for offer in loanOffers[cur]:
			onOrderBalances[cur] = onOrderBalances.get(cur, 0) + Decimal(offer['amount'])		
		if dryRun == False and Decimal(lendingBalances[cur]) +  onOrderBalances.get(cur, 0) > minLoanSize:
			for offer in loanOffers[cur]:
				msg = bot.cancelLoanOffer(cur,offer['id'])
				log.cancelOrders(cur, msg)

	lendingBalances = bot.returnAvailableAccountBalances("lending")['lending']
```

**Comment by rnevet** [comment]
How about not canceling open loans that are in the spread,
I think updating the loans every 1min reduces the chance of lending, especially if you are in a wall (or minLendingRate)... ideas?

**Comment by Evanito** [comment]
Can we detect walls?
Say if the ledger is

- 1$ 40 coins
- 1.01$ 42 coins
- 1.02$ 4billion coins

Through the API can we detect a daily lending volume? If we can assign a number to the activity of a coin's lending market, then we can choose what we define as a wall. The more active the market the less likely we would be to avoid walls, because those walls are more likely to break.

Maybe this should be a side issue.
