### ISSUE TITLE
I am having to disable 'sanity checks' minDailyRate & maxDailyRate

### ISSUE THREAD

**Issue by Methodise** [Mikadily/poloniexlendingbot#82]
But by doing so, everything works as expected (I have specified my min and max as a percent, rather than a decimal).

**Comment by Evanito** [comment]
Thank you for this comment I have already seen this inconsistency and a roadmap has been made to address this issue in #85

**Comment by rnevet** [comment]
@Methodise
Could you give some details on what values you are trying to use? I don't see a functional error in the sanity checks... unless you are trying to for very low rates.

**Comment by Evanito** [comment]
Closing because user error.
