### ISSUE TITLE
ERROR: 'provided'

### ISSUE THREAD

**Issue by JCBauza** [Mikadily/poloniexlendingbot#90]
Hi,

I am not verse in php so I am having a hard time. I have configured the default.cfg with just the API keys but I get the following error right off the bat:

Obtaining settings from config file.
Welcome to Poloniex Lending Bot
2016-07-21 14:04:12 ERROR: 'provided'
Traceback (most recent call last):
  File "lendingbot.py", line 457, in <module>
    refreshTotalLended()
  File "lendingbot.py", line 230, in refreshTotalLended
    for item in cryptoLended["provided"]:
KeyError: 'provided'

Thanks!

**Comment by JCBauza** [comment]
My bad, the API Key was not enabled for the IP address so that's why it was getting probably an empty result set that was causing the error. I would suggest validation of the communication first and a catch of empty result sets to avoid this. Clearly user fault but would be nice for user experience to catch those mistakes. Thanks!

**Comment by Evanito** [comment]
Yeah, we really need to add guidelines that link to https://github.com/Mikadily/poloniexlendingbot/wiki/FAQ-(Trouble-shooting)
