### ISSUE TITLE
Stops at Lended

### ISSUE THREAD

**Issue by GoldZeus** [Mikadily/poloniexlendingbot#98]
Hello everyone, great project!
I'm just wondering if it's normal that when I double click lendingbot (after the first time and configured my default.cfg) The bot stay at _Lended:_

Here's a screenshot:
![Lended](http://image.prntscr.com/image/46107c5635004b40996027df19c08884.png)

It has been like an hour or so and it just stays there.
I have enough funds in my poloniex account (0.03 bitcoins) and have the default settings, only updated my API key and secret.

Thank you for your help.

**Comment by rnevet** [comment]
Have you tried restarting the bot?

**Comment by GoldZeus** [comment]
Hello and thanks for the help.
Yes I have tried many times now to restart it, even tried with the web interface.

Here is my default.cfg file:
```
[BOT]
#sleep between active iterations, time in seconds (1-3600)
sleeptimeactive = 60

#sleep between inactive iterations, time in seconds (1-3600)
#set to same as sleeptimeactive to disable
sleeptimeinactive = 300

#minimum daily lend rate in percent (0.00003-0.05)
mindailyrate = 0.04

#max rate. 2% is good choice because it's default at margin trader interface.
#5% is max to be accepted by the exchange (0.00003-0.05)
maxdailyrate = 2

#The number of offers to split the available balance across the [gaptop, gapbottom] range. (1-20)
spreadlend = 3

#The depth of lendbook (in percent of lendable balance) to move through
#before placing the first (gapbottom) and last (gaptop) offer.
#If gapbottom is set to 0, the first offer will be at the lowest possible rate.
#However some low value is recommended (say 10%) to skip dust offers.
gapbottom = 10
gaptop = 200

#Daily lend rate threshold after which we offer lends for 60 days as opposed to 2.
#If set to 0 all offers will be placed for a 2 day period (0.00003-0.05)
sixtydaythreshold = 0.2

#Minimum loan size the minimum size of offers to make, bigger values prevent the bot from loaning small available amounts but reduce loans fragmentation
minloansize = 0.001

#AutoRenew - if set to 1 the bot will set the AutoRenew flag for the loans when you stop it (Ctrl+C) and clear the AutoRenew flag when on started
autorenew = 0

#custom config per coin, useful when closing positions etc.
#syntax: ["COIN:mindailyrate:maxactiveamount",...]
#if maxactive amount is 0 - stop lending this coin. in the future you'll be able to limit amount to be lent.
#coinconfig = ["BTC:0.18:1","CLAM:0.6:1"]

#this option creates a json log file instead of console output which includes the most recent status
#uncomment both jsonfile and jsonlogsize to enable
jsonfile = www/botlog.json
#limits the amount of log lines to save
jsonlogsize = 200
#enables a webserver for the www folder, in order to easily use the lendingbot.html with the json log
startWebServer = true
```

And here's what I see when enabled the web server:
![Poloniex](http://image.prntscr.com/image/e85befaa2c6b4923b1438568049232fc.png)

Again nothing.
Thanks.

**Comment by rnevet** [comment]
I would recommend not starting the web interface till you have it running without, easier to see errors with the cmd.

Make sure your btc is actually in the Lending account, not Exchange or Margin - I would suspect that this behavior might be how it looks if there are no coins to lend.
Otherwise, since you are trying to lend BTC and mindailyrate is 0.04 and current offers are around 0.02 - I would try reducing that value to 0.02.

**Comment by GoldZeus** [comment]
You were right; this was the problem!
Thanks a lot for your help !!
