### ISSUE TITLE
Watch config file for changes

### ISSUE THREAD

**Issue by denravonska** [Mikadily/poloniexlendingbot#99]
It would be neat if the config file could be monitored (using watchdog or something similar) for changes and reread whenever it is updated. As it is now you have to close the bot, make the changes and relaunch it, but it takes a while before the OS releases the listening socket for the web server. As a result, it launches without the web server and has to be killed/respawned numerous times.

**Comment by rnevet** [comment]
This sounds like a very env setup specific issue, I didn't encounter any issues on Windows nor Ubuntu. I just change the config file and restart the bot.

**Comment by denravonska** [comment]
Could be, encountered it in Linux though I assume it applies to all UNIX variants (see [here](http://www.softlab.ntua.gr/facilities/documentation/unix/unix-socket-faq/unix-socket-faq-4.html#ss4.2)). It may take up to 4 minutes before you can use the socket again.

I still think it would be more convenient if the bot would apply the changes immediately when it was added to the config and I'm willing to give the implementation a shot. It looks like it will require some config loading rewrite and there might be issues with config load errors.

**Comment by rnevet** [comment]
Actually, I'm not running the bot webserver on Unbunto - which is why I don't need to restart the webserver either and probably why I'm not experiencing this issue.

You can look into this answer on SO to see if one of the suggested solution works:
http://stackoverflow.com/questions/6380057/python-binding-socket-address-already-in-use

In any case, I think an easier solution to your issue is starting the webserver from a separate script so it doesn't need to be restarted for config changes. 
See the startWebServer server functions.

If you are looking into watching the config file for changes keep in mind that the bot code is cross platform and not meant only for Linux.

**Comment by denravonska** [comment]
The bot uses SocketServer and SimpleHTTPServer so I guess we have little to say in the way of socket options. I guess we could either switch to a more sophisticated server or split the web server and bot, but I'm not sure it would solve the issue. I realise that it might be somewhat of a niche request, but since it's so useful when tweaking the config and not rocket science to implement I think it should still be doable. It would also come in handy if the bot could be configurable from the web server in the future.

I know it's cross platform which is why I suggested the watchdog package :)

**Comment by rnevet** [comment]
I actually think the answer in SO should fit our case:
http://stackoverflow.com/a/35363839/348378

And it should also easy to copy the server functions out to a different script - that should for sure solve the issue since you could restart the bot without restarting the server at all.

**Comment by denravonska** [comment]
Ah, the SO suggestion should work. I'll try it later when I get the problematic computer back up. Interestingly, I do not get the error in newer Ubuntus so the server problem might be a non-issue in the real world.

I'll try to give the config update a go. It might not be portably doable without relying on a third party component though.

**Comment by Evanito** [comment]
Okay, I see there haven't been any updates here in a while.
Right now I have a concern that our bot is "prokaryotic" and we are trying to add new features.

The bot does not take many things into consideration when running, it does not use a worker system (which we really should if we are going to add more features), and does not watch to make sure it doesn't go over Poloniex's API requests per second limit. These are all features we should consider before bringing in another requirement. (Speaking of, we don't use pip at all.)

**Comment by yura-pakhuchiy** [comment]
Automatic config re-read maybe not expected by user, and can lead to unexpected results, especially in case of editor will auto-save in the middle of edit. Sending SIGUSR or SIGHUP to process is standard practice in *nix world to signal daemon to re-read it config.

**Comment by rnevet** [comment]
I agree with @yura-pakhuchiy  and would vote to close this suggestion.
